/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.estoque;

import connection.ConnectionFactory;
import exception.EnvioExcecao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import ui.controle.Controle;
import ui.principal.Estoque;

/**
 *
 * @author 1113778771
 */
public class EnviarEstoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form EnviarEstoque
     */
    private static EnviarEstoque enviarEstoqueInstance;

    public static EnviarEstoque getInstancia() {
        return new EnviarEstoque();
    }

    public EnviarEstoque() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seletorDeArquivos = new javax.swing.JFileChooser();
        enviarEstoque = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        enderecoArquivo = new javax.swing.JLabel();

        setTitle("ENVIAR ESTOQUE");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/upload.png"))); // NOI18N

        seletorDeArquivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seletorDeArquivosMouseClicked(evt);
            }
        });
        seletorDeArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorDeArquivosActionPerformed(evt);
            }
        });

        enviarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/upload.png"))); // NOI18N
        enviarEstoque.setText("ENVIAR ESTOQUE");
        enviarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarEstoqueActionPerformed(evt);
            }
        });

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancelar.png"))); // NOI18N
        cancelar.setText("CANCELAR");

        enderecoArquivo.setText("ARQUIVO SELECIONADO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seletorDeArquivos, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enderecoArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviarEstoque)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(seletorDeArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarEstoque)
                    .addComponent(cancelar)
                    .addComponent(enderecoArquivo))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelar, enderecoArquivo});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seletorDeArquivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seletorDeArquivosMouseClicked

    }//GEN-LAST:event_seletorDeArquivosMouseClicked

    private void seletorDeArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorDeArquivosActionPerformed
        if (seletorDeArquivos.getSelectedFile() != null) {
            enderecoArquivo.setText("ARQUIVO SELECIONADO: " + seletorDeArquivos.getSelectedFile().getPath().toString());
        }
    }//GEN-LAST:event_seletorDeArquivosActionPerformed

    private void enviarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarEstoqueActionPerformed
        new Thread() {
            @Override
            public void run() {
                try {
                    Estoque.loadingVisible("CONECTANDO AO SERVIDOR...");
                    String dirDestino = Controle.retornaDirEstoque();
                    String destino = Controle.ESTOQUE_NAME + seletorDeArquivos.getSelectedFile().getPath().substring(
                            seletorDeArquivos.getSelectedFile().getPath().indexOf("."));
                    if (ConnectionFactory.uploadSSH(seletorDeArquivos.getSelectedFile().getPath(), destino, Controle.retornaDirEstoque())) {
                        JOptionPane.showMessageDialog(null, "ESTOQUE ENVIADO COM SUCESSO!", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                        Estoque.loadingHide();
                        return;
                    }
                } catch (SQLException ex) {
                    EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
                    EnvioExcecao.envio();
                }
            }
        }.start();


    }//GEN-LAST:event_enviarEstoqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel enderecoArquivo;
    private javax.swing.JButton enviarEstoque;
    private javax.swing.JFileChooser seletorDeArquivos;
    // End of variables declaration//GEN-END:variables
}
