/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.relatorios.detalhamento;

import com.itextpdf.text.BaseColor;
import entities.sisgrafex.NotaCredito;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.lowagie.text.Element;
import entities.sisgrafex.Cliente;
import entities.sisgrafex.Faturamento;
import entities.sisgrafex.Orcamento;
import entities.sisgrafex.OrdemProducao;
import entities.sisgrafex.ProdOrcamento;
import exception.EnvioExcecao;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import model.dao.OrdemProducaoDAO;
import model.dao.ClienteDAO;
import model.dao.NotaDAO;
import model.dao.OrcamentoDAO;
import ui.controle.Controle;

/**
 *
 * @author claudio
 */
public class RelatorioDetalhamento extends javax.swing.JInternalFrame {

    DefaultListModel model = new DefaultListModel();
    public static Cliente cliente;
    int qtdSelecionada = 0;

    private JLabel loading;

    private static RelatorioDetalhamento relatoriosNotasCredito;

    public static RelatorioDetalhamento getInstancia(JLabel loading) {
        return new RelatorioDetalhamento(loading);
    }

    private double saldoNC;
    private double saldoFat;
    private double saldoEmAberto;

    public RelatorioDetalhamento(JLabel loading) {
        initComponents();
        this.loading = loading;
        listPesquisaCliente.setModel(model);
        estadoInicial();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCliente = new javax.swing.ButtonGroup();
        grupoOrientacao = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jrbPorCodigo = new javax.swing.JRadioButton();
        jftfCodigoCliente = new javax.swing.JFormattedTextField();
        jrbPorNome = new javax.swing.JRadioButton();
        jtfNomeCliente = new javax.swing.JTextField();
        jcbTipoPessoa = new javax.swing.JComboBox<>();
        listPesquisaCliente = new javax.swing.JList<>();
        lblOrientacao = new javax.swing.JLabel();
        rBtnRetrato = new javax.swing.JRadioButton();
        rBtnPaisagem = new javax.swing.JRadioButton();
        botaoGeraRelatorio = new javax.swing.JButton();

        setTitle("DETALHAMENTO DE CLIENTE");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/notaCredito.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 340));

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        grupoCliente.add(jrbPorCodigo);
        jrbPorCodigo.setText("POR CÓDIGO");
        jrbPorCodigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbPorCodigoItemStateChanged(evt);
            }
        });

        jftfCodigoCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        grupoCliente.add(jrbPorNome);
        jrbPorNome.setText("POR NOME");
        jrbPorNome.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbPorNomeItemStateChanged(evt);
            }
        });
        jrbPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPorNomeActionPerformed(evt);
            }
        });

        jtfNomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNomeClienteKeyReleased(evt);
            }
        });

        jcbTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - PESSOA FÍSICA (PF)", "2 - PESSOA JURÍDICA (PJ)" }));

        listPesquisaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPesquisaClienteMouseClicked(evt);
            }
        });

        lblOrientacao.setText("ORIENTAÇÃO:");

        grupoOrientacao.add(rBtnRetrato);
        rBtnRetrato.setText("RETRATO");

        grupoOrientacao.add(rBtnPaisagem);
        rBtnPaisagem.setText("PAISAGEM");

        botaoGeraRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/confirma.png"))); // NOI18N
        botaoGeraRelatorio.setText("GERAR RELATÓRIO");
        botaoGeraRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGeraRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbPorCodigo)
                        .addGap(32, 32, 32)
                        .addComponent(jcbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jftfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbPorNome)
                        .addGap(44, 44, 44)
                        .addComponent(jtfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblOrientacao)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(rBtnPaisagem))
                            .addComponent(rBtnRetrato)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(listPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(botaoGeraRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrientacao)
                            .addComponent(rBtnRetrato)
                            .addComponent(rBtnPaisagem)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(botaoGeraRelatorio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(listPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblOrientacao, rBtnPaisagem, rBtnRetrato});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jrbPorNome, jtfNomeCliente});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcbTipoPessoa, jftfCodigoCliente, jrbPorCodigo});

        jTabbedPane1.addTab("CLIENTE", new javax.swing.ImageIcon(getClass().getResource("/icones/cliente.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPorNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbPorNomeActionPerformed

    private void jtfNomeClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeClienteKeyReleased
        try {
            model.removeAllElements();

            for (String nome : ClienteDAO.retornaPesquisaClientesAproximada(jtfNomeCliente.getText())) {
                model.addElement(nome);
            }

            if (model.isEmpty()) {
                listPesquisaCliente.setVisible(false);
            } else {
                listPesquisaCliente.setVisible(true);
            }
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio(loading);
        }
    }//GEN-LAST:event_jtfNomeClienteKeyReleased

    private void jrbPorCodigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbPorCodigoItemStateChanged
        if (jrbPorCodigo.isSelected() == true) {
            jcbTipoPessoa.setEnabled(true);
            jftfCodigoCliente.setEnabled(true);
            jtfNomeCliente.setEnabled(false);
            listPesquisaCliente.setVisible(false);
        } else if (jrbPorNome.isSelected() == true) {
            jcbTipoPessoa.setEnabled(false);
            jftfCodigoCliente.setEnabled(false);
            jtfNomeCliente.setEnabled(true);
            listPesquisaCliente.setVisible(false);
        } else {
            jcbTipoPessoa.setEnabled(false);
            jftfCodigoCliente.setEnabled(false);
            jtfNomeCliente.setEnabled(false);
            listPesquisaCliente.setVisible(false);
        }
    }//GEN-LAST:event_jrbPorCodigoItemStateChanged

    private void jrbPorNomeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbPorNomeItemStateChanged
        if (jrbPorCodigo.isSelected() == true) {
            jcbTipoPessoa.setEnabled(true);
            jftfCodigoCliente.setEnabled(true);
            jtfNomeCliente.setEnabled(false);
            listPesquisaCliente.setVisible(false);
        } else if (jrbPorNome.isSelected() == true) {
            jcbTipoPessoa.setEnabled(false);
            jftfCodigoCliente.setEnabled(false);
            jtfNomeCliente.setEnabled(true);
            listPesquisaCliente.setVisible(false);
        } else {
            jcbTipoPessoa.setEnabled(false);
            jftfCodigoCliente.setEnabled(false);
            jtfNomeCliente.setEnabled(false);
            listPesquisaCliente.setVisible(false);
        }
    }//GEN-LAST:event_jrbPorNomeItemStateChanged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        listPesquisaCliente.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void listPesquisaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPesquisaClienteMouseClicked
        try {
            jtfNomeCliente.setText(listPesquisaCliente.getSelectedValue());
            cliente = ClienteDAO.retornaTipoCodClienteRelatorio(jtfNomeCliente.getText());
            listPesquisaCliente.setVisible(false);
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio(loading);
        }
    }//GEN-LAST:event_listPesquisaClienteMouseClicked

    private void botaoGeraRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGeraRelatorioActionPerformed
        geraRelatorio();
    }//GEN-LAST:event_botaoGeraRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoGeraRelatorio;
    private javax.swing.ButtonGroup grupoCliente;
    private javax.swing.ButtonGroup grupoOrientacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcbTipoPessoa;
    private javax.swing.JFormattedTextField jftfCodigoCliente;
    private javax.swing.JRadioButton jrbPorCodigo;
    private javax.swing.JRadioButton jrbPorNome;
    private javax.swing.JTextField jtfNomeCliente;
    private javax.swing.JLabel lblOrientacao;
    private javax.swing.JList<String> listPesquisaCliente;
    private javax.swing.JRadioButton rBtnPaisagem;
    private javax.swing.JRadioButton rBtnRetrato;
    // End of variables declaration//GEN-END:variables
    //ESTADOS DA UI
    public void estadoInicial() {
        //CLIENTE
        jcbTipoPessoa.setEnabled(false);
        jftfCodigoCliente.setEnabled(false);
        jtfNomeCliente.setEnabled(false);
        listPesquisaCliente.setVisible(false);
    }

    /**
     * Constrói o documento
     */
    public void geraRelatorio() {

        saldoNC = 0d;
        saldoFat = 0d;
        saldoEmAberto = 0d;

        com.itextpdf.text.Document document = new com.itextpdf.text.Document(PageSize.A4, 30, 20, 20, 30);

        String valor = null;

        new Thread("Gera o relatório detalhado do cliente") {
            @Override
            public void run() {

                loading.setVisible(true);
                loading.setText("GERANDO RELATÓRIO...");

                String hora = Controle.horaPadraoDiretorio.format(new Date());
                String data = Controle.dataPadraoDiretorio.format(new Date());

                try {
                    if (System.getProperty("os.name").toLowerCase().contains("windows")) {
                        PdfWriter.getInstance(document, new FileOutputStream(Controle.urlTempWindows + data + hora + ".pdf"));
                    } else {
                        PdfWriter.getInstance(document, new FileOutputStream(Controle.urlTempUnix + data + hora + ".pdf"));
                    }

                    document.setMargins(20, 20, 20, 20);
                    if (rBtnPaisagem.isSelected()) {
                        document.setPageSize(PageSize.A4.rotate());
                    } else {
                        document.setPageSize(PageSize.A4);
                    }

                    document.open();

                    document.add(new Paragraph(new Phrase("DETALHAMENTO DE CLIENTE - "
                            + "DATA E HORA DE EMISSÃO: "
                            + data
                            + " "
                            + hora
                            + " - SISGRAFEX\n\n", FontFactory.getFont("arial.ttf", 9))));

                    document.add(new Paragraph("\n"));

                    if (jrbPorCodigo.isSelected()) {
                        cliente = ClienteDAO.selInfoNota((byte) (jcbTipoPessoa.getSelectedIndex() + 1), Integer.valueOf(jftfCodigoCliente.getText()));
                    }

                    Paragraph p = new Paragraph(Element.ALIGN_CENTER, cliente.getCodigo() + " - " + cliente.getNome());
                    p.setAlignment(Element.ALIGN_CENTER);
                    document.add(p);

                    document.add(new Paragraph("\n"));

                    PdfPTable tabelaNotasCredito = geraTabelaNotasCredito();
                    tabelaNotasCredito.setWidthPercentage(100);
                    document.add(tabelaNotasCredito);
                    document.add(new Paragraph("\n"));
                    PdfPTable tabelaFaturamentos = geraTabelaFaturamentos();
                    tabelaFaturamentos.setWidthPercentage(100);
                    document.add(tabelaFaturamentos);
                    document.add(new Paragraph("\n"));
                    PdfPTable tabelaOrdemProducao = geraTabelaOrdemProducao();
                    tabelaOrdemProducao.setWidthPercentage(100);
                    document.add(tabelaOrdemProducao);
                    document.add(new Paragraph("\n\n"));
                    PdfPTable tabelaPropostas = geraTabelaPropostasOrcamento();
                    tabelaPropostas.setWidthPercentage(100);
                    document.add(tabelaPropostas);
                    
                    document.add(new Phrase("(1) - O valor total referente as propostas de orçamento não é somado ao saldo final.", FontFactory.getFont("arial.ttf", 8, Font.BOLD)));
                    
                    document.add(new Paragraph("\n\n"));
                    PdfPTable tabelaSaldoFinal = geraTabelaSaldoFinal();
                    tabelaSaldoFinal.setWidthPercentage(100);
                    document.add(tabelaSaldoFinal);
                    

                    document.close();

                    if (System.getProperty("os.name").toLowerCase().contains("windows")) {
                        java.awt.Desktop.getDesktop().open(new File(Controle.urlTempWindows + data + hora + ".pdf"));
                    } else {
                        java.awt.Desktop.getDesktop().open(new File(Controle.urlTempUnix + data + hora + ".pdf"));
                    }
                    loading.setVisible(false);
                } catch (IOException | DocumentException ex) {
                    EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
                    EnvioExcecao.envio(loading);
                } catch (SQLException ex) {
                    EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
                    EnvioExcecao.envio(loading);
                }
            }
        }.start();
    }

    /**
     * Retorna a tabela de notas de crédito
     *
     * @return
     */
    public PdfPTable geraTabelaNotasCredito() {
        PdfPTable retorno = new PdfPTable(new float[]{5f, 5f, 5f});
        Double vlrTotal = 0d;

        try {
            if (jrbPorCodigo.isSelected()) {
                cliente = new Cliente();
                cliente.setTipoPessoa((byte) (jcbTipoPessoa.getSelectedIndex() + 1));
                cliente.setCodigo(Integer.valueOf(jftfCodigoCliente.getText()));
            }

            //CABEÇALHO---------------------------------------------------------
            PdfPCell celula = new PdfPCell();
            celula = new PdfPCell(new Phrase("NOTAS DE CRÉDITO", FontFactory.getFont("arial.ttf", 8, Font.BOLD, BaseColor.WHITE)));
            celula.setBackgroundColor(BaseColor.BLACK);
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            celula.setColspan(3);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("NOTA DE CRÉDITO", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("DATA", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("VALOR", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);

            for (NotaCredito nc : NotaDAO.retornaNCCliente(cliente.getCodigo(), cliente.getTipoPessoa())) {
                celula = new PdfPCell(new Phrase(String.valueOf(nc.getCod()), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);
                celula = new PdfPCell(new Phrase(nc.getData(), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);
                celula = new PdfPCell(new Phrase("(+) R$ " + Controle.formatoVlrPadrao.format(nc.getValor()), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);
                vlrTotal += nc.getValor();
            }
            saldoNC = vlrTotal;
            celula = new PdfPCell(new Phrase("VALOR TOTAL: (+) R$ " + Controle.formatoVlrPadrao.format(vlrTotal), FontFactory.getFont("arial.ttf", 8, Font.BOLD)));
            celula.setColspan(3);
            celula.setHorizontalAlignment(Element.ALIGN_RIGHT);
            retorno.addCell(celula);
            return retorno;
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio(loading);
            return null;
        }
    }

    /**
     * Retorna a tabela de faturamentos
     *
     * @return
     */
    public PdfPTable geraTabelaFaturamentos() {
        PdfPTable retorno = new PdfPTable(new float[]{5f, 5f, 5f, 5f, 5f});
        Double vlrTotal = 0d;

        try {
            if (jrbPorCodigo.isSelected()) {
                cliente = new Cliente();
                cliente.setTipoPessoa((byte) (jcbTipoPessoa.getSelectedIndex() + 1));
                cliente.setCodigo(Integer.valueOf(jftfCodigoCliente.getText()));
            }

            //CABEÇALHO---------------------------------------------------------
            PdfPCell celula = new PdfPCell();
            celula = new PdfPCell(new Phrase("FATURAMENTOS", FontFactory.getFont("arial.ttf", 8, Font.BOLD, BaseColor.WHITE)));
            celula.setBackgroundColor(BaseColor.BLACK);
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            celula.setColspan(5);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("PROPOSTA DE ORÇAMENTO", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("ORDEM DE PRODUÇÃO", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("DATA", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("PRODUTO", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("VALOR", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);

            for (Faturamento fat : NotaDAO.retornaFatCliente(cliente.getCodigo(), cliente.getTipoPessoa())) {
                celula = new PdfPCell(new Phrase(String.valueOf(fat.getCodOrc()), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);
                celula = new PdfPCell(new Phrase(String.valueOf(fat.getCodOp()), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);
                celula = new PdfPCell(new Phrase(Controle.dataPadrao.format(fat.getDtFat()), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);
                celula = new PdfPCell(new Phrase(fat.getDescricaoProduto(), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);
                celula = new PdfPCell(new Phrase("(-) R$ " + Controle.formatoVlrPadrao.format(fat.getVlrFat()), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);
                vlrTotal += fat.getVlrFat();
            }
            saldoFat = vlrTotal;
            celula = new PdfPCell(new Phrase("VALOR TOTAL: (-) R$ " + Controle.formatoVlrPadrao.format(vlrTotal), FontFactory.getFont("arial.ttf", 8, Font.BOLD)));
            celula.setColspan(5);
            celula.setHorizontalAlignment(Element.ALIGN_RIGHT);
            retorno.addCell(celula);
            return retorno;
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio(loading);
            return null;
        }
    }

    /**
     * Retorna as ordem de produção do cliente
     *
     * @return
     */
    public PdfPTable geraTabelaOrdemProducao() {
        PdfPTable retorno = new PdfPTable(new float[]{5f, 5f, 5f, 5f, 5f, 5f, 5f});
        Double vlrTotal = 0d;

        try {
            if (jrbPorCodigo.isSelected()) {
                cliente = new Cliente();
                cliente.setTipoPessoa((byte) (jcbTipoPessoa.getSelectedIndex() + 1));
                cliente.setCodigo(Integer.valueOf(jftfCodigoCliente.getText()));
            }

            //CABEÇALHO---------------------------------------------------------
            PdfPCell celula = new PdfPCell();
            celula = new PdfPCell(new Phrase("ORDEM DE PRODUÇÃO", FontFactory.getFont("arial.ttf", 8, Font.BOLD, BaseColor.WHITE)));
            celula.setBackgroundColor(BaseColor.BLACK);
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            celula.setColspan(7);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("PROPOSTA DE ORÇAMENTO", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("ORDEM DE PRODUÇÃO", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("EMISSÃO", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("ENTREGA PREVISTA", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("PRODUTO", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("STATUS", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("VALOR", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);

            //Indicador que adicionou o cabeçalho da tabela
            boolean addCabecalho = false;

            List<OrdemProducao> listaOp = OrdemProducaoDAO.retornaOrdemProducaoCliente(cliente.getCodigo(), cliente.getTipoPessoa());

            for (OrdemProducao op : listaOp) {
                if (op.getStatus() == 11 || op.getStatus() == 13) {
                    if (!addCabecalho) {
                        celula = new PdfPCell(new Phrase("FINALIZADAS", FontFactory.getFont("arial.ttf", 6, Font.BOLD, BaseColor.WHITE)));
                        celula.setBackgroundColor(BaseColor.BLACK);
                        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                        celula.setColspan(7);
                        retorno.addCell(celula);
                        addCabecalho = true;
                    }
                    celula = new PdfPCell(new Phrase(String.valueOf(op.getOrcBase()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(String.valueOf(op.getCodigo()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(Controle.dataPadrao.format(op.getDataEmissao()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(Controle.dataPadrao.format(op.getDataEntrega()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(op.getDescricao(), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(Controle.stsOp.get(op.getStatus() - 1).toString(), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    if (op.getStatus() == 11) {
                        if (NotaDAO.verificaFaturamento(op.getCodigo())) {
                            celula = new PdfPCell(new Phrase("(FATURADA) R$ " + Controle.formatoVlrPadrao.format(op.getValorParcial()), FontFactory.getFont("arial.ttf", 6)));
                            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                            retorno.addCell(celula);
                        } else {
                            celula = new PdfPCell(new Phrase("(NÃO FATURADA) R$ " + Controle.formatoVlrPadrao.format(op.getValorParcial()), FontFactory.getFont("arial.ttf", 6)));
                            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                            retorno.addCell(celula);
                        }
                    } else {
                        celula = new PdfPCell(new Phrase("-", FontFactory.getFont("arial.ttf", 6)));
                        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                        retorno.addCell(celula);
                    }

                }
            }

            addCabecalho = false;

            for (OrdemProducao op : listaOp) {
                if (op.getStatus() == 12) {
                    if (!addCabecalho) {
                        celula = new PdfPCell(new Phrase("ENTREGUES PARCIALMENTE", FontFactory.getFont("arial.ttf", 6, Font.BOLD, BaseColor.WHITE)));
                        celula.setBackgroundColor(BaseColor.BLACK);
                        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                        celula.setColspan(7);
                        retorno.addCell(celula);
                        addCabecalho = true;
                    }
                    celula = new PdfPCell(new Phrase(String.valueOf(op.getOrcBase()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(String.valueOf(op.getCodigo()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(Controle.dataPadrao.format(op.getDataEmissao()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(Controle.dataPadrao.format(op.getDataEntrega()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(op.getDescricao(), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(Controle.stsOp.get(op.getStatus() - 1).toString(), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    float faturada = NotaDAO.retornaVlrOpEntregueParcial(op.getCodigo());
                    float emAberto = op.getValorParcial() - faturada;
                    celula = new PdfPCell(new Phrase("(TOTAL) R$ " + Controle.formatoVlrPadrao.format(op.getValorParcial()) + "\n\n(FATURADO) R$ "
                            + Controle.formatoVlrPadrao.format(faturada) + "\n\n (PRODUÇÃO) (-) R$ "
                            + Controle.formatoVlrPadrao.format(emAberto),
                            FontFactory.getFont("arial.ttf", 6)
                    ));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    vlrTotal += emAberto;
                }
            }

            addCabecalho = false;

            for (OrdemProducao op : listaOp) {
                if (op.getStatus() != 12 && op.getStatus() != 11 && op.getStatus() != 13) {
                    if (!addCabecalho) {
                        celula = new PdfPCell(new Phrase("EM PRODUÇÃO", FontFactory.getFont("arial.ttf", 6, Font.BOLD, BaseColor.WHITE)));
                        celula.setBackgroundColor(BaseColor.BLACK);
                        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                        celula.setColspan(7);
                        retorno.addCell(celula);
                        addCabecalho = true;
                    }
                    celula = new PdfPCell(new Phrase(String.valueOf(op.getOrcBase()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(String.valueOf(op.getCodigo()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(Controle.dataPadrao.format(op.getDataEmissao()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(Controle.dataPadrao.format(op.getDataEntrega()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(op.getDescricao(), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase(Controle.stsOp.get(op.getStatus() - 1).toString(), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    celula = new PdfPCell(new Phrase("(-) R$ " + Controle.formatoVlrPadrao.format(op.getValorParcial()), FontFactory.getFont("arial.ttf", 6)));
                    celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                    retorno.addCell(celula);
                    vlrTotal += op.getValorParcial();
                }
            }
            saldoEmAberto = vlrTotal;
            celula = new PdfPCell(new Phrase("VALOR TOTAL: (-) R$ " + Controle.formatoVlrPadrao.format(vlrTotal), FontFactory.getFont("arial.ttf", 8, Font.BOLD)));
            celula.setColspan(7);
            celula.setHorizontalAlignment(Element.ALIGN_RIGHT);
            retorno.addCell(celula);
            return retorno;
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio(loading);
            return null;
        }
    }

    /**
     * Retorna as propostas de orçamento relacionadas ao cliente
     *
     * @return
     */
    public PdfPTable geraTabelaPropostasOrcamento() {
        PdfPTable retorno = new PdfPTable(new float[]{5f, 5f, 5f, 5f, 5f, 5f});
        Double vlrTotal = 0d;

        if (jrbPorCodigo.isSelected()) {
            cliente = new Cliente();
            cliente.setTipoPessoa((byte) (jcbTipoPessoa.getSelectedIndex() + 1));
            cliente.setCodigo(Integer.valueOf(jftfCodigoCliente.getText()));
        }

        try {
            //CABEÇALHO---------------------------------------------------------
            PdfPCell celula = new PdfPCell();
            celula = new PdfPCell(new Phrase("PROPOSTAS DE ORÇAMENTO", FontFactory.getFont("arial.ttf", 8, Font.BOLD, BaseColor.WHITE)));
            celula.setBackgroundColor(BaseColor.BLACK);
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            celula.setColspan(6);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("Nº DA PROPOSTA", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("DATA DE EMISSÃO", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("DATA DE VALIDADE", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("PRODUTOS", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("STATUS", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);
            celula = new PdfPCell(new Phrase("VALOR", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
            celula.setHorizontalAlignment(Element.ALIGN_CENTER);
            retorno.addCell(celula);

            for (Orcamento orcamento : OrcamentoDAO.retornaPropostasCliente(cliente)) {
                celula = new PdfPCell(new Phrase(String.valueOf(orcamento.getCod()), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);
                celula = new PdfPCell(new Phrase(orcamento.getDataEmissaoString(), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);
                celula = new PdfPCell(new Phrase(orcamento.getDataValidadeString(), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);

                String produtos = "";
                int ordem = 1;
                for (ProdOrcamento produto : OrcamentoDAO.retornaProdutosOrcamento(orcamento)) {
                    produtos += ordem + " - " + "CÓD: " + produto.getCodProduto() + "/" + produto.getDescricaoProduto() + "/QTD: " + produto.getQuantidade() + "/UNIT: R$ " + Controle.formatoVlrPadrao.format(produto.getPrecoUnitario());
                    produtos += "\n\n";
                    ordem += 1;
                }
                celula = new PdfPCell(new Phrase(produtos, FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);
                celula = new PdfPCell(new Phrase(orcamento.getStatusString(), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);
                celula = new PdfPCell(new Phrase("R$ " + Controle.formatoVlrPadrao.format(orcamento.getValorTotal()), FontFactory.getFont("arial.ttf", 6)));
                celula.setHorizontalAlignment(Element.ALIGN_CENTER);
                retorno.addCell(celula);

                vlrTotal += orcamento.getValorTotal();

            }
            celula = new PdfPCell(new Phrase("VALOR TOTAL: (-) R$ " + Controle.formatoVlrPadrao.format(vlrTotal) + " *(1)", FontFactory.getFont("arial.ttf", 8, Font.BOLD)));
            celula.setColspan(6);
            celula.setHorizontalAlignment(Element.ALIGN_RIGHT);
            retorno.addCell(celula);
            return retorno;
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio(loading);
            return null;
        }
    }

    /**
     * Retorna a tabela de saldo final
     *
     * @return
     */
    public PdfPTable geraTabelaSaldoFinal() {
        PdfPTable retorno = new PdfPTable(new float[]{5f, 5f, 5f, 5f});
        Double vlrTotal = 0d;

        PdfPCell celula = new PdfPCell();
        celula = new PdfPCell(new Phrase("SALDO FINAL", FontFactory.getFont("arial.ttf", 8, Font.BOLD, BaseColor.WHITE)));
        celula.setBackgroundColor(BaseColor.BLACK);
        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
        celula.setColspan(4);
        retorno.addCell(celula);

        celula = new PdfPCell(new Phrase("CRÉDITO", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
        retorno.addCell(celula);
        celula = new PdfPCell(new Phrase("DÉBITO", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
        retorno.addCell(celula);
        celula = new PdfPCell(new Phrase("EM PRODUÇÃO", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
        retorno.addCell(celula);
        celula = new PdfPCell(new Phrase("TOTAL", FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
        retorno.addCell(celula);

        celula = new PdfPCell(new Phrase("R$ (+) " + Controle.formatoVlrPadrao.format(saldoNC), FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
        retorno.addCell(celula);
        celula = new PdfPCell(new Phrase("R$ (-) " + Controle.formatoVlrPadrao.format(saldoFat), FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
        retorno.addCell(celula);
        celula = new PdfPCell(new Phrase("R$ (-) " + Controle.formatoVlrPadrao.format(saldoEmAberto), FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
        retorno.addCell(celula);
        vlrTotal = saldoNC - (saldoFat + saldoEmAberto);
        celula = new PdfPCell(new Phrase("R$ " + Controle.formatoVlrPadrao.format(vlrTotal), FontFactory.getFont("arial.ttf", 6, Font.BOLD)));
        celula.setHorizontalAlignment(Element.ALIGN_CENTER);
        retorno.addCell(celula);

        return retorno;
    }

}
