/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.orcamentos.cadastros;

import exception.EnvioExcecao;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.MateriaisCadastroBEAN;
import model.dao.MateriaisCadastroDAO;
import ui.controle.Controle;

/**
 *
 * @author spd3
 */
public class MateriaisCadastro extends javax.swing.JFrame {

    /**
     * Creates new form materiais_cadastro
     */
    public MateriaisCadastro() {
        initComponents();

        excluir.setEnabled(false);
        editar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        descricao_materiais = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cadastrar_material = new javax.swing.JButton();
        estoque_seg_materiais = new javax.swing.JFormattedTextField();
        preco_custo_materiais = new javax.swing.JFormattedTextField();
        preco_venda_materiais = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_consulta = new javax.swing.JTable();
        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tipo_pesquisa = new javax.swing.JComboBox<String>();
        texto_pesquisa = new javax.swing.JTextField();
        botao_pesquisar = new javax.swing.JButton();
        mostra_todos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("DESCRIÇÃO:");

        jLabel8.setText("ESTOQUE DE SEGURANÇA:");

        jLabel9.setText("PREÇO CUSTO:");

        jLabel10.setText("PREÇO VENDA:");

        cadastrar_material.setText("CADASTRAR");
        cadastrar_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_materialActionPerformed(evt);
            }
        });

        estoque_seg_materiais.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        preco_custo_materiais.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        preco_custo_materiais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preco_custo_materiaisActionPerformed(evt);
            }
        });

        preco_venda_materiais.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadastrar_material)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricao_materiais, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(estoque_seg_materiais, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(preco_custo_materiais, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(preco_venda_materiais, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {preco_custo_materiais, preco_venda_materiais});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricao_materiais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(estoque_seg_materiais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(preco_custo_materiais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(preco_venda_materiais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(cadastrar_material)
                .addContainerGap())
        );

        jTabbedPane1.addTab("NOVO", jPanel2);

        tabela_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIÇÃO", "ESTOQUE DE SEGURANÇA", "PREÇO CUSTO", "PREÇO VENDA", "DATA ALTERAÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_consultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_consulta);
        if (tabela_consulta.getColumnModel().getColumnCount() > 0) {
            tabela_consulta.getColumnModel().getColumn(2).setPreferredWidth(90);
        }

        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        excluir.setText("EXCLUIR");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        jLabel13.setText("PESQUISA POR:");

        tipo_pesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Código", "Descrição", "Estoque de Segurança", "Preço Custo", "Preço Venda", "Data de Alteração" }));
        tipo_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_pesquisaActionPerformed(evt);
            }
        });

        botao_pesquisar.setText("PESQUISAR");
        botao_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesquisarActionPerformed(evt);
            }
        });

        mostra_todos.setText("MOSTRAR TODOS");
        mostra_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostra_todosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tipo_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(texto_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao_pesquisar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editar))
                            .addComponent(mostra_todos, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostra_todos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar)
                    .addComponent(excluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONSULTAS", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_materialActionPerformed
        try {
            MateriaisCadastroBEAN mcBEAN = new MateriaisCadastroBEAN();
            
            if (descricao_materiais.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Insira um valor no campo Descrição.");
                return;
            } else {
                mcBEAN.setDescricao(descricao_materiais.getText().toUpperCase());
            }
            
            if (estoque_seg_materiais.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Insira um valor no campo Estoque de Segurança.");
                return;
            } else {
                String n2 = String.valueOf(estoque_seg_materiais.getValue().toString());
                mcBEAN.setEstoque_seg(Integer.valueOf(n2));
            }
            
            String n2 = String.valueOf(preco_custo_materiais.getValue().toString());
            n2 = n2.replace(",", ".");
            mcBEAN.setPreco_custo(Float.valueOf(n2));
            
            n2 = String.valueOf(preco_venda_materiais.getValue().toString());
            n2 = n2.replace(",", ".");
            mcBEAN.setPreco_venda(Float.valueOf(n2));
            
            mcBEAN.setData_alteracao(Controle.dataPadrao.format(new Date()));
            
            MateriaisCadastroDAO.create(mcBEAN);
            
            limpa();
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio();
        }
    }//GEN-LAST:event_cadastrar_materialActionPerformed

    private void tabela_consultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_consultaMouseClicked
        editar.setEnabled(true);
        excluir.setEnabled(true);
    }//GEN-LAST:event_tabela_consultaMouseClicked

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        try {
            MateriaisEditar materiaisEditar = new MateriaisEditar();
            materiaisEditar.setLocationRelativeTo(null);
            materiaisEditar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            int cod = (int) tabela_consulta.getValueAt(tabela_consulta.getSelectedRow(), 0);
            for (MateriaisCadastroBEAN mcBEAN : MateriaisCadastroDAO.carregaEdicao(cod)) {
                MateriaisEditar.codigo_editar.setValue(mcBEAN.getCod());
                MateriaisEditar.descricao_editar.setText(mcBEAN.getDescricao());
                MateriaisEditar.estoque_seg_editar.setValue(mcBEAN.getEstoque_seg());
                MateriaisEditar.preco_custo_editar.setValue(mcBEAN.getPreco_custo());
                MateriaisEditar.preco_venda_editar.setValue(mcBEAN.getPreco_venda());
            }
            materiaisEditar.setVisible(true);
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio();
        }
    }//GEN-LAST:event_editarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        MateriaisCadastroDAO mcDAO = new MateriaisCadastroDAO();
        int cod = (int) tabela_consulta.getValueAt(tabela_consulta.getSelectedRow(), 0);
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Excluir registro nº " + cod + "?", "Confirmação de exclusão", dialogButton);
        if (dialogResult == 0) {
            try {
                mcDAO.excluir_registro(cod);
                DefaultTableModel modelo_consulta = (DefaultTableModel) tabela_consulta.getModel();
                modelo_consulta.setNumRows(0);
                for (MateriaisCadastroBEAN mcBEAN : MateriaisCadastroDAO.mostraTodos()) {
                    modelo_consulta.addRow(new Object[]{
                        mcBEAN.getCod(),
                        mcBEAN.getDescricao(),
                        mcBEAN.getEstoque_seg(),
                        mcBEAN.getPreco_custo(),
                        mcBEAN.getPreco_venda(),
                        mcBEAN.getData_alteracao()});
                }
            } catch (SQLException ex) {
                EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio();
            }
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void tipo_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_pesquisaActionPerformed

    private void botao_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesquisarActionPerformed
        try {
            DefaultTableModel modeloConsulta = (DefaultTableModel) tabela_consulta.getModel();
            modeloConsulta.setNumRows(0);
            for (MateriaisCadastroBEAN mcBEAN : MateriaisCadastroDAO.consulta((String) tipo_pesquisa.getSelectedItem(), texto_pesquisa.getText())) {
                modeloConsulta.addRow(new Object[]{
                    mcBEAN.getCod(),
                    mcBEAN.getDescricao(),
                    mcBEAN.getEstoque_seg(),
                    mcBEAN.getPreco_custo(),
                    mcBEAN.getPreco_venda(),
                    mcBEAN.getData_alteracao()});
            }
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio();
        }
    }//GEN-LAST:event_botao_pesquisarActionPerformed

    private void mostra_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostra_todosActionPerformed
        try {
            DefaultTableModel modeloConsulta = (DefaultTableModel) tabela_consulta.getModel();
            modeloConsulta.setNumRows(0);
            for (MateriaisCadastroBEAN mcBEAN : MateriaisCadastroDAO.mostraTodos()) {
                modeloConsulta.addRow(new Object[]{
                    mcBEAN.getCod(),
                    mcBEAN.getDescricao(),
                    mcBEAN.getEstoque_seg(),
                    mcBEAN.getPreco_custo(),
                    mcBEAN.getPreco_venda(),
                    mcBEAN.getData_alteracao()});
            }
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio();
        }
    }//GEN-LAST:event_mostra_todosActionPerformed

    private void preco_custo_materiaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preco_custo_materiaisActionPerformed

    }//GEN-LAST:event_preco_custo_materiaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriaisCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriaisCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriaisCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriaisCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MateriaisCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_pesquisar;
    private javax.swing.JButton cadastrar_material;
    private javax.swing.JTextField descricao_materiais;
    private javax.swing.JButton editar;
    private javax.swing.JFormattedTextField estoque_seg_materiais;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton mostra_todos;
    private javax.swing.JFormattedTextField preco_custo_materiais;
    private javax.swing.JFormattedTextField preco_venda_materiais;
    public static javax.swing.JTable tabela_consulta;
    private javax.swing.JTextField texto_pesquisa;
    private javax.swing.JComboBox<String> tipo_pesquisa;
    // End of variables declaration//GEN-END:variables
    public void limpa() {
        descricao_materiais.setText("");
        estoque_seg_materiais.setText("");
        preco_custo_materiais.setText("");
        preco_venda_materiais.setText("");
    }

}
