/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.orcamentos.operacoes;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import ui.principal.GerenteJanelas;

/**
 *
 * @author claud
 */
public class AdicionarObservacaoProdutoFrame extends javax.swing.JInternalFrame {

    public static int linha;

    private JLabel loading;
    private GerenteJanelas gj;

    private static AdicionarObservacaoProdutoFrame observacaoProduto;

    public static AdicionarObservacaoProdutoFrame getInstancia(JLabel loading, GerenteJanelas gj) {
        return new AdicionarObservacaoProdutoFrame(loading, gj);
    }

    /**
     * Creates new form ObservacaoProduto
     */
    public AdicionarObservacaoProdutoFrame(JLabel loading, GerenteJanelas gj) {
        initComponents();
        this.loading = loading;
        this.gj = gj;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        observacaoProdutoText = new javax.swing.JTextArea();
        confirmarObservacaoProduto = new javax.swing.JButton();

        setTitle("ADICIONAR OBSERVAÇÃO DO PRODUTO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar.png"))); // NOI18N

        observacaoProdutoText.setColumns(20);
        observacaoProdutoText.setLineWrap(true);
        observacaoProdutoText.setRows(5);
        observacaoProdutoText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(observacaoProdutoText);

        confirmarObservacaoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/confirma.png"))); // NOI18N
        confirmarObservacaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarObservacaoProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmarObservacaoProduto)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmarObservacaoProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarObservacaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarObservacaoProdutoActionPerformed
        int retorno = 0;
        for (int i = 0; i < OrcamentoPrincipalFrame.tabelaProdutos.getRowCount(); i++) {
            if (OrcamentoPrincipalFrame.tabelaProdutos.getValueAt(i, 5).equals(observacaoProdutoText.getText())) {
                JOptionPane.showMessageDialog(null, "A DESCRIÇÃO JÁ EXISTE PARA UM MESMO PRODUTO JÁ CADASTRADO.");
                return;
            } else {
                retorno = 1;
            }
        }

        if (retorno == 1) {
            OrcamentoPrincipalFrame.tabelaProdutos.setValueAt(observacaoProdutoText.getText().toUpperCase(), linha, 5);
            OrcamentoPrincipalFrame.observacaoProduto.setEnabled(false);
        }
        this.dispose();
    }//GEN-LAST:event_confirmarObservacaoProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmarObservacaoProduto;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea observacaoProdutoText;
    // End of variables declaration//GEN-END:variables
}
