/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.principal;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import ui.administrador.AnaliseErros;
import ui.administrador.Avisos;
import ui.administrador.FuncionarioCadastro;
import ui.administrador.SelData;
import ui.controle.Controle;
import ui.login.TelaAutenticacao;

/**
 *
 * @author claud
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();

        atualizacao.setVisible(false);
        
        new Thread("Atualizações administrador") {
            @Override
            public void run() {
                while (true) {
                    try {
                        try {
                            if(Controle.verificaVersao(TelaAutenticacao.getCodVersao(), 
                                    TelaAutenticacao.getUpdate())){
                                atualizacao.setVisible(true);
                            }
                            Thread.sleep(600000);
                        } catch (SQLException ex) {
                            Thread.sleep(600000);
                            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (InterruptedException ex) {
                        Thread.interrupted();
                        Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }.start();
        
        Controle.setDefaultGj(new GerenteJanelas(areaDeTrabalho));
        Controle.defineStatus(statusPane);
        loadingHide();

        URL url = this.getClass().getResource("/ui/login/logo.png");
        Image imagemLogo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemLogo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogSelOrigem = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusPane = new javax.swing.JTextPane();
        ImageIcon icon = new ImageIcon(getClass().getResource("/ui/principal/brasaoGraficaBala-475x288.png"));
        Image image = icon.getImage();
        areaDeTrabalho = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                Dimension d = areaDeTrabalho.getSize();
                g.drawImage(image,(d.width - 475) / 2,(d.height - 288) / 2,475,288,null);
            }

        };
        loading = new javax.swing.JLabel();
        atualizacao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        mnAtendentes = new javax.swing.JMenuItem();
        menDados = new javax.swing.JMenuItem();
        menAvisos = new javax.swing.JMenuItem();
        menAnaliseErr = new javax.swing.JMenuItem();
        modulos = new javax.swing.JMenu();
        sair = new javax.swing.JMenu();

        javax.swing.GroupLayout dialogSelOrigemLayout = new javax.swing.GroupLayout(dialogSelOrigem.getContentPane());
        dialogSelOrigem.getContentPane().setLayout(dialogSelOrigemLayout);
        dialogSelOrigemLayout.setHorizontalGroup(
            dialogSelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogSelOrigemLayout.setVerticalGroup(
            dialogSelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jScrollPane1.setViewportView(statusPane);

        areaDeTrabalho.setBackground(java.awt.Color.lightGray);

        javax.swing.GroupLayout areaDeTrabalhoLayout = new javax.swing.GroupLayout(areaDeTrabalho);
        areaDeTrabalho.setLayout(areaDeTrabalhoLayout);
        areaDeTrabalhoLayout.setHorizontalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        areaDeTrabalhoLayout.setVerticalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/orcamentos/operacoes/carregando.gif"))); // NOI18N

        atualizacao.setBackground(new java.awt.Color(255, 102, 102));
        atualizacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atualizacao.setText("Uma atualização do sistema está disponível. Quando finalizar as operações, feche esta instância e abra novamente pela INTRANET.");
        atualizacao.setOpaque(true);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menu.png"))); // NOI18N
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        mnAtendentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/atendentes.png"))); // NOI18N
        mnAtendentes.setText("CADASTRO DE ATENDENTES");
        mnAtendentes.setToolTipText("");
        mnAtendentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAtendentesMouseClicked(evt);
            }
        });
        mnAtendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAtendentesActionPerformed(evt);
            }
        });
        menu.add(mnAtendentes);

        menDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/dados.png"))); // NOI18N
        menDados.setText("ORIGEM DE DADOS");
        menDados.setToolTipText("Definir a origem dos dados do sistema");
        menDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menDadosActionPerformed(evt);
            }
        });
        menu.add(menDados);

        menAvisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/tutoriais.png"))); // NOI18N
        menAvisos.setText("AVISOS");
        menAvisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAvisosActionPerformed(evt);
            }
        });
        menu.add(menAvisos);

        menAnaliseErr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/suporte.png"))); // NOI18N
        menAnaliseErr.setText("ANÁLISE DE ERROS");
        menAnaliseErr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAnaliseErrActionPerformed(evt);
            }
        });
        menu.add(menAnaliseErr);

        jMenuBar1.add(menu);

        modulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/modulos.png"))); // NOI18N
        modulos.setText("MÓDULOS");
        modulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modulosMousePressed(evt);
            }
        });
        modulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulosActionPerformed(evt);
            }
        });
        jMenuBar1.add(modulos);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        sair.setText("SAIR");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sairMousePressed(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
            .addComponent(loading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(areaDeTrabalho)
            .addComponent(atualizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaDeTrabalho)
                .addGap(4, 4, 4)
                .addComponent(atualizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnAtendentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAtendentesMouseClicked

    }//GEN-LAST:event_mnAtendentesMouseClicked

    private void mnAtendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAtendentesActionPerformed
        Controle.getDefaultGj().abrirJanelas(FuncionarioCadastro.getInstancia(), "CADASTRO DE ATENDENTES");
    }//GEN-LAST:event_mnAtendentesActionPerformed

    private void modulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulosActionPerformed

    }//GEN-LAST:event_modulosActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        
    }//GEN-LAST:event_menuActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed

    }//GEN-LAST:event_sairActionPerformed

    private void menDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menDadosActionPerformed
        Controle.getDefaultGj().abrirJanelas(SelData.getInstancia(), "SELETOR DE ORIGEM DE DADOS");
    }//GEN-LAST:event_menDadosActionPerformed

    private void modulosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modulosMousePressed
        ModulosInt modulos = new ModulosInt();
        modulos.setTitle("MÓDULOS");
        modulos.setLocationRelativeTo(null);
        modulos.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
        modulos.setVisible(true);
    }//GEN-LAST:event_modulosMousePressed

    private void sairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMousePressed
        Controle.sair(this);
    }//GEN-LAST:event_sairMousePressed

    private void menAvisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAvisosActionPerformed
        Controle.getDefaultGj().abrirJanelas(Avisos.getInstancia(loading), "AVISOS");
    }//GEN-LAST:event_menAvisosActionPerformed

    private void menAnaliseErrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAnaliseErrActionPerformed
        Controle.getDefaultGj().abrirJanelas(AnaliseErros.getInstancia(loading), "ANÁLISE DE ERROS");
    }//GEN-LAST:event_menAnaliseErrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaDeTrabalho;
    public static javax.swing.JLabel atualizacao;
    private javax.swing.JDialog dialogSelOrigem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel loading;
    private javax.swing.JMenuItem menAnaliseErr;
    private javax.swing.JMenuItem menAvisos;
    private javax.swing.JMenuItem menDados;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem mnAtendentes;
    private javax.swing.JMenu modulos;
    private javax.swing.JMenu sair;
    public static javax.swing.JTextPane statusPane;
    // End of variables declaration//GEN-END:variables
public static void loadingVisible(String texto) {
        loading.setVisible(true);
        loading.setText(texto);
    }

    public static void loadingHide() {
        loading.setVisible(false);
        loading.setText("");
    }
}
