/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.principal;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import ui.cadastros.clientes.ClienteCadastro;
import ui.cadastros.notas.NCFrame;
import ui.cadastros.notas.FatFrame;
import ui.consulta.simatex.ConsultaSimatexFrame;
import ui.controle.Controle;
import ui.login.TelaAutenticacao;
import ui.orcamentos.operacoes.OrcamentoPrincipalFrame;
import ui.ordemProducao.consultas.OpConsultaFrame;
import static ui.principal.Financeiro.loading;
import ui.relatorios.detalhamento.RelatorioDetalhamento;
import ui.relatorios.financeiro.RelatorioFat;
import ui.relatorios.financeiro.RelatorioFinanceiro;
import ui.relatorios.financeiro.RelatoriosNotasCredito;
import ui.relatorios.orcamentos.RelatorioOrcamentos;
import ui.relatorios.ordemProducao.RelatoriosOrdemProducao;
import ui.relatorios.papeis.RelatoriosPapeis;

/**
 *
 * @author claud
 */
public class OrdenadorInt extends javax.swing.JFrame {

    /**
     * Creates new form Ordenador
     */
    public OrdenadorInt() {
        initComponents();
        
        atualizacao.setVisible(false);
        
        StringBuilder avProd = new StringBuilder();
        new Thread("Atualizações ordenador interno") {
            @Override
            public void run() {
                while (true) {
                    try {
                        try {
                            taAvisos.setText("* Dicas de utilização:\n\n"
                                    + Controle.retornaAvOrd()
                            );
                            
                            if(Controle.verificaVersao(TelaAutenticacao.getCodVersao(), 
                                    TelaAutenticacao.getUpdate())){
                                atualizacao.setVisible(true);
                            }
                            Thread.sleep(600000);
                        } catch (SQLException ex) {
                            Thread.sleep(600000);
                            Logger.getLogger(OrcamentoFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (InterruptedException ex) {
                        Thread.interrupted();
                        Logger.getLogger(OrdenadorInt.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        }.start();

//        URL url = this.getClass().getResource("/ui/login/logo.png");
//        Image imagemLogo = Toolkit.getDefaultToolkit().getImage(url);
//        this.setIconImage(imagemLogo);

        Controle.setDefaultGj(new GerenteJanelas(areaDeTrabalho));
        Controle.defineStatus(statusPane);
        loadingHide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        statusPane = new javax.swing.JTextPane();
        //ImageIcon icon = new ImageIcon(getClass().getResource("/ui/principal/brasaoGraficaBala-475x288.png"));
        //Image image = icon.getImage();
        areaDeTrabalho = new javax.swing.JDesktopPane(){

            //    public void paintComponent(Graphics g){
                //        Dimension d = areaDeTrabalho.getSize();
                //        g.drawImage(image,(d.width - 475) / 2,(d.height - 288) / 2,475,288,null);
                //    }

        };
        jScrollPane2 = new javax.swing.JScrollPane();
        taAvisos = new javax.swing.JTextArea();
        loading = new javax.swing.JLabel();
        atualizacao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        cadastroClientes = new javax.swing.JMenuItem();
        orcamentos = new javax.swing.JMenuItem();
        ordensProducao = new javax.swing.JMenuItem();
        notasVenda = new javax.swing.JMenuItem();
        notasCredito = new javax.swing.JMenuItem();
        consultaSimatex = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        relatoriosOrc = new javax.swing.JMenuItem();
        relatoriosOp = new javax.swing.JMenuItem();
        relatoriosNv = new javax.swing.JMenuItem();
        relatoriosNc = new javax.swing.JMenuItem();
        relatoriosPapeis = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        modulos = new javax.swing.JMenu();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jScrollPane1.setViewportView(statusPane);

        areaDeTrabalho.setBackground(java.awt.Color.lightGray);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("AVISOS"));
        jScrollPane2.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setFocusable(false);
        jScrollPane2.setRequestFocusEnabled(false);

        taAvisos.setEditable(false);
        taAvisos.setColumns(20);
        taAvisos.setLineWrap(true);
        taAvisos.setRows(5);
        taAvisos.setWrapStyleWord(true);
        taAvisos.setDragEnabled(true);
        jScrollPane2.setViewportView(taAvisos);

        areaDeTrabalho.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout areaDeTrabalhoLayout = new javax.swing.GroupLayout(areaDeTrabalho);
        areaDeTrabalho.setLayout(areaDeTrabalhoLayout);
        areaDeTrabalhoLayout.setHorizontalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaDeTrabalhoLayout.createSequentialGroup()
                .addContainerGap(574, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        areaDeTrabalhoLayout.setVerticalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaDeTrabalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/orcamentos/operacoes/carregando.gif"))); // NOI18N

        atualizacao.setBackground(new java.awt.Color(255, 102, 102));
        atualizacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atualizacao.setText("Uma atualização do sistema está disponível. Quando finalizar as operações, feche esta instância e abra novamente pela INTRANET.");
        atualizacao.setOpaque(true);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menu.png"))); // NOI18N
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        cadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadastros.png"))); // NOI18N
        cadastroClientes.setText("CADASTRO DE CLIENTES ");
        cadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClientesActionPerformed(evt);
            }
        });
        menu.add(cadastroClientes);

        orcamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/orçamento.png"))); // NOI18N
        orcamentos.setText("ORÇAMENTOS - ORÇAMENTAÇÃO");
        orcamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orcamentosMouseClicked(evt);
            }
        });
        orcamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orcamentosActionPerformed(evt);
            }
        });
        menu.add(orcamentos);

        ordensProducao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/carrinho.png"))); // NOI18N
        ordensProducao.setText("ORDENS DE PRODUÇÃO - PRODUÇÃO");
        ordensProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordensProducaoActionPerformed(evt);
            }
        });
        menu.add(ordensProducao);

        notasVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/faturamento.png"))); // NOI18N
        notasVenda.setText("FATURAMENTOS - EXPEDIÇÃO");
        notasVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notasVendaActionPerformed(evt);
            }
        });
        menu.add(notasVenda);

        notasCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/notaCredito.png"))); // NOI18N
        notasCredito.setText("NOTAS DE CRÉDITO - FINANCEIRO (COMERCIAL)");
        notasCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notasCreditoActionPerformed(evt);
            }
        });
        menu.add(notasCredito);

        consultaSimatex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/consulta_banco.png"))); // NOI18N
        consultaSimatex.setText("CONSULTA DE MATERIAL SIMATEX - ESTOQUE");
        consultaSimatex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaSimatexActionPerformed(evt);
            }
        });
        menu.add(consultaSimatex);

        jMenuBar1.add(menu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/relatorios.png"))); // NOI18N
        jMenu1.setText("RELATÓRIOS");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        relatoriosOrc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/orçamento.png"))); // NOI18N
        relatoriosOrc.setText("RELATÓRIO DE ORÇAMENTOS");
        relatoriosOrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriosOrcActionPerformed(evt);
            }
        });
        jMenu1.add(relatoriosOrc);

        relatoriosOp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/carrinho.png"))); // NOI18N
        relatoriosOp.setText("RELATÓRIO DE ORDEM DE PRODUÇÃO");
        relatoriosOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriosOpActionPerformed(evt);
            }
        });
        jMenu1.add(relatoriosOp);

        relatoriosNv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/faturamento.png"))); // NOI18N
        relatoriosNv.setText("RELATÓRIO DE FATURAMENTOS");
        relatoriosNv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriosNvActionPerformed(evt);
            }
        });
        jMenu1.add(relatoriosNv);

        relatoriosNc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/notaCredito.png"))); // NOI18N
        relatoriosNc.setText("RELATÓRIO DE NOTAS DE CRÉDITO");
        relatoriosNc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriosNcActionPerformed(evt);
            }
        });
        jMenu1.add(relatoriosNc);

        relatoriosPapeis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/papeis.png"))); // NOI18N
        relatoriosPapeis.setText("RELATÓRIO DE CONSUMO DE PAPÉIS");
        relatoriosPapeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriosPapeisActionPerformed(evt);
            }
        });
        jMenu1.add(relatoriosPapeis);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/financeiro.png"))); // NOI18N
        jMenuItem1.setText("RELATÓRIO FINANCEIRO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/detalhes.png"))); // NOI18N
        jMenuItem2.setText("DETALHAMENTO DE CLIENTE");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        modulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/modulos.png"))); // NOI18N
        modulos.setText("MÓDULOS");
        modulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modulosMousePressed(evt);
            }
        });
        modulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulosActionPerformed(evt);
            }
        });
        jMenuBar1.add(modulos);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        sair.setText("SAIR");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sairMousePressed(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(loading, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
            .addComponent(areaDeTrabalho)
            .addComponent(atualizacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaDeTrabalho)
                .addGap(4, 4, 4)
                .addComponent(atualizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orcamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orcamentosMouseClicked

    }//GEN-LAST:event_orcamentosMouseClicked

    private void orcamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orcamentosActionPerformed
        Controle.getDefaultGj().abrirJanelas(OrcamentoPrincipalFrame.getInstancia(loading, Controle.getDefaultGj(), (byte) 2), "ORÇAMENTOS");
        OrcamentoPrincipalFrame.tabsOrcamento.setSelectedIndex(1);
        OrcamentoPrincipalFrame.p1.setSelectedIndex(5);
        OrcamentoPrincipalFrame.p2.setSelectedItem("3 - ENVIADO PARA OD");
        OrcamentoPrincipalFrame.setCLASSE_PAI((byte) 2);
        OrcamentoPrincipalFrame.pesquisar();
    }//GEN-LAST:event_orcamentosActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed

    }//GEN-LAST:event_menuActionPerformed

    private void modulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulosActionPerformed

    }//GEN-LAST:event_modulosActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed

    }//GEN-LAST:event_sairActionPerformed

    private void cadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClientesActionPerformed
        Controle.getDefaultGj().abrirJanelas(ClienteCadastro.getInstancia(loading, Controle.getDefaultGj(), (byte) 2), "CADASTRO DE CLIENTES");
    }//GEN-LAST:event_cadastroClientesActionPerformed

    private void ordensProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordensProducaoActionPerformed
        Controle.getDefaultGj().abrirJanelas(OpConsultaFrame.getInstancia(loading, (byte) 2), "CONSULTA DE ORDEM DE PRODUÇÃO");
    }//GEN-LAST:event_ordensProducaoActionPerformed

    private void notasVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notasVendaActionPerformed
        Controle.getDefaultGj().abrirJanelas(FatFrame.getInstancia(loading, Controle.getDefaultGj()), "NOTAS DE VENDA");
    }//GEN-LAST:event_notasVendaActionPerformed

    private void notasCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notasCreditoActionPerformed
        Controle.getDefaultGj().abrirJanelas(NCFrame.getInstancia(loading, Controle.getDefaultGj()), "NOTAS DE CRÉDITO");
    }//GEN-LAST:event_notasCreditoActionPerformed

    private void modulosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modulosMousePressed
        ModulosInt modulos = new ModulosInt();
        modulos.setTitle("MÓDULOS");
        modulos.setLocationRelativeTo(null);
        modulos.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
        modulos.setVisible(true);
    }//GEN-LAST:event_modulosMousePressed

    private void sairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMousePressed
        Controle.sair(this);
    }//GEN-LAST:event_sairMousePressed

    private void consultaSimatexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaSimatexActionPerformed
        Controle.getDefaultGj().abrirJanelas(ConsultaSimatexFrame.getInstancia(loading), "CONSULTA DE MATERIAL SIMATEX");
    }//GEN-LAST:event_consultaSimatexActionPerformed

    private void relatoriosOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosOpActionPerformed
        Controle.getDefaultGj().abrirJanelas(RelatoriosOrdemProducao.getInstancia(loading), "RELATÓRIO DE ORDEM DE PRODUÇÃO");
    }//GEN-LAST:event_relatoriosOpActionPerformed

    private void relatoriosNvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosNvActionPerformed
        Controle.getDefaultGj().abrirJanelas(RelatorioFat.getInstancia(loading), "RELATÓRIO DE FATURAMENTOS");
    }//GEN-LAST:event_relatoriosNvActionPerformed

    private void relatoriosNcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosNcActionPerformed
        Controle.getDefaultGj().abrirJanelas(RelatoriosNotasCredito.getInstancia(loading), "RELATÓRIO DE NOTAS DE CRÉDITO");
    }//GEN-LAST:event_relatoriosNcActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void relatoriosOrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosOrcActionPerformed
        Controle.getDefaultGj().abrirJanelas(RelatorioOrcamentos.getInstancia(loading), "RELATÓRIO DE ORÇAMENTOS");
    }//GEN-LAST:event_relatoriosOrcActionPerformed

    private void relatoriosPapeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosPapeisActionPerformed
        Controle.getDefaultGj().abrirJanelas(RelatoriosPapeis.getInstancia(loading), "RELATÓRIO DE CONSUMO DE PAPÉIS");
    }//GEN-LAST:event_relatoriosPapeisActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Controle.getDefaultGj().abrirJanelas(RelatorioFinanceiro.getInstancia(loading), "RELATÓRIOS - FINANCEIRO");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Controle.getDefaultGj().abrirJanelas(RelatorioDetalhamento.getInstancia(loading), "RELATÓRIOS - DETALHAMENTO");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenadorInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenadorInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenadorInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenadorInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenadorInt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaDeTrabalho;
    public static javax.swing.JLabel atualizacao;
    private javax.swing.JMenuItem cadastroClientes;
    private javax.swing.JMenuItem consultaSimatex;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel loading;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu modulos;
    private javax.swing.JMenuItem notasCredito;
    private javax.swing.JMenuItem notasVenda;
    private javax.swing.JMenuItem orcamentos;
    private javax.swing.JMenuItem ordensProducao;
    private javax.swing.JMenuItem relatoriosNc;
    private javax.swing.JMenuItem relatoriosNv;
    private javax.swing.JMenuItem relatoriosOp;
    private javax.swing.JMenuItem relatoriosOrc;
    private javax.swing.JMenuItem relatoriosPapeis;
    private javax.swing.JMenu sair;
    private javax.swing.JTextPane statusPane;
    private javax.swing.JTextArea taAvisos;
    // End of variables declaration//GEN-END:variables
public static void loadingVisible(String texto) {
        loading.setVisible(true);
        loading.setText(texto);
    }

    public static void loadingHide() {
        loading.setVisible(false);
        loading.setText("");
    }
}
