/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.principal;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import ui.cadastros.notas.NCFrame;
import ui.cadastros.notas.FatFrame;
import ui.controle.Controle;
import ui.login.TelaAutenticacao;
import ui.orcamentos.operacoes.OrcamentoPrincipalFrame;
import ui.ordemProducao.consultas.OpConsultaFrame;

/**
 *
 * @author claud
 */
public class OrdenadorExt extends javax.swing.JFrame {

    /**
     * Creates new form Ordenador
     */
    public OrdenadorExt() {
        initComponents();

        atualizacao.setVisible(false);
        
        new Thread("Atualizações ordenador externo") {
            @Override
            public void run() {
                while (true) {
                    try {
                        try {
                            if(Controle.verificaVersao(TelaAutenticacao.codVersao, 
                                    TelaAutenticacao.atualizacao)){
                                atualizacao.setVisible(true);
                            }
                            Thread.sleep(600000);
                        } catch (SQLException ex) {
                            Thread.sleep(600000);
                            Logger.getLogger(OrdenadorExt.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (InterruptedException ex) {
                        Thread.interrupted();
                        Logger.getLogger(OrdenadorExt.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }.start();
        
        URL url = this.getClass().getResource("/ui/login/logo.png");
        Image imagemLogo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemLogo);

        Controle.setDefaultGj(new GerenteJanelas(areaDeTrabalho));
        Controle.defineStatus(statusPane);
        loadingHide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        statusPane = new javax.swing.JTextPane();
        ImageIcon icon = new ImageIcon(getClass().getResource("/ui/principal/brasaoGraficaBala-475x288.png"));
        Image image = icon.getImage();
        areaDeTrabalho = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                Dimension d = areaDeTrabalho.getSize();
                g.drawImage(image,(d.width - 475) / 2,(d.height - 288) / 2,475,288,null);
            }

        };
        loading = new javax.swing.JLabel();
        atualizacao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        orcamentos = new javax.swing.JMenuItem();
        ordensProducao = new javax.swing.JMenuItem();
        notasVenda = new javax.swing.JMenuItem();
        notasCredito = new javax.swing.JMenuItem();
        modulos = new javax.swing.JMenu();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jScrollPane1.setViewportView(statusPane);

        areaDeTrabalho.setBackground(java.awt.Color.lightGray);

        javax.swing.GroupLayout areaDeTrabalhoLayout = new javax.swing.GroupLayout(areaDeTrabalho);
        areaDeTrabalho.setLayout(areaDeTrabalhoLayout);
        areaDeTrabalhoLayout.setHorizontalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        areaDeTrabalhoLayout.setVerticalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/orcamentos/operacoes/carregando.gif"))); // NOI18N

        atualizacao.setBackground(new java.awt.Color(255, 102, 102));
        atualizacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atualizacao.setText("Uma atualização do sistema está disponível. Quando finalizar as operações, feche esta instância e abra novamente pela INTRANET.");
        atualizacao.setOpaque(true);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menu.png"))); // NOI18N
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        orcamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/orçamento.png"))); // NOI18N
        orcamentos.setText("ORÇAMENTOS - ORÇAMENTAÇÃO");
        orcamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orcamentosMouseClicked(evt);
            }
        });
        orcamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orcamentosActionPerformed(evt);
            }
        });
        menu.add(orcamentos);

        ordensProducao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/carrinho.png"))); // NOI18N
        ordensProducao.setText("ORDENS DE PRODUÇÃO - PRODUÇÃO");
        ordensProducao.setEnabled(false);
        ordensProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordensProducaoActionPerformed(evt);
            }
        });
        menu.add(ordensProducao);

        notasVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/faturamento.png"))); // NOI18N
        notasVenda.setText("FATURAMENTOS - EXPEDIÇÃO");
        notasVenda.setEnabled(false);
        notasVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notasVendaActionPerformed(evt);
            }
        });
        menu.add(notasVenda);

        notasCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/notaCredito.png"))); // NOI18N
        notasCredito.setText("NOTAS DE CRÉDITO - FINANCEIRO (COMERCIAL)");
        notasCredito.setEnabled(false);
        notasCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notasCreditoActionPerformed(evt);
            }
        });
        menu.add(notasCredito);

        jMenuBar1.add(menu);

        modulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/modulos.png"))); // NOI18N
        modulos.setText("MÓDULOS");
        modulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modulosMousePressed(evt);
            }
        });
        modulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulosActionPerformed(evt);
            }
        });
        jMenuBar1.add(modulos);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        sair.setText("SAIR");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sairMousePressed(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
            .addComponent(loading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(areaDeTrabalho)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(atualizacao, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaDeTrabalho)
                .addGap(27, 27, 27)
                .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(530, Short.MAX_VALUE)
                    .addComponent(atualizacao)
                    .addGap(33, 33, 33)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orcamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orcamentosMouseClicked

    }//GEN-LAST:event_orcamentosMouseClicked

    private void orcamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orcamentosActionPerformed
        Controle.getDefaultGj().abrirJanelas(OrcamentoPrincipalFrame.getInstancia(loading, Controle.getDefaultGj(), (byte) 2), "ORÇAMENTOS");
        OrcamentoPrincipalFrame.estadoOdExt();
        
        new Thread("Pesquisa orçamentos ordenador externo") {
            @Override
            public void run() {
                OrcamentoPrincipalFrame.pesquisar();
            }
        }.start();
    }//GEN-LAST:event_orcamentosActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed

    }//GEN-LAST:event_menuActionPerformed

    private void modulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulosActionPerformed

    }//GEN-LAST:event_modulosActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed

    }//GEN-LAST:event_sairActionPerformed

    private void notasVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notasVendaActionPerformed
        Controle.getDefaultGj().abrirJanelas(FatFrame.getInstancia(loading,Controle.getDefaultGj()), "NOTAS DE VENDA");
    }//GEN-LAST:event_notasVendaActionPerformed

    private void notasCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notasCreditoActionPerformed
        Controle.getDefaultGj().abrirJanelas(NCFrame.getInstancia(loading,Controle.getDefaultGj()), "NOTAS DE CRÉDITO");
    }//GEN-LAST:event_notasCreditoActionPerformed

    private void modulosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modulosMousePressed
        ModulosInt modulos = new ModulosInt();
        modulos.setTitle("MÓDULOS");
        modulos.setLocationRelativeTo(null);
        modulos.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
        modulos.setVisible(true);
    }//GEN-LAST:event_modulosMousePressed

    private void sairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMousePressed
        Controle.sair(this);
    }//GEN-LAST:event_sairMousePressed

    private void ordensProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordensProducaoActionPerformed
        Controle.getDefaultGj().abrirJanelas(OpConsultaFrame.getInstancia(loading), "CONSULTA DE ORDEM DE PRODUÇÃO");
    }//GEN-LAST:event_ordensProducaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenadorExt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenadorExt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenadorExt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenadorExt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenadorExt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaDeTrabalho;
    public static javax.swing.JLabel atualizacao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel loading;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu modulos;
    private javax.swing.JMenuItem notasCredito;
    private javax.swing.JMenuItem notasVenda;
    private javax.swing.JMenuItem orcamentos;
    private javax.swing.JMenuItem ordensProducao;
    private javax.swing.JMenu sair;
    private javax.swing.JTextPane statusPane;
    // End of variables declaration//GEN-END:variables
public static void loadingVisible(String texto) {
        loading.setVisible(true);
        loading.setText(texto);
    }

    public static void loadingHide() {
        loading.setVisible(false);
        loading.setText("");
    }
}
