/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.administrador;

import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.tabelas.AnaliseErrTableModel;
import ui.erros.ErroBEAN;
import ui.erros.ErroDAO;

/**
 *
 * @author claud
 */
public class AnaliseErros extends javax.swing.JInternalFrame {

    private JLabel loading;

    public static AnaliseErros getInstancia(JLabel loading) {
        return new AnaliseErros(loading);
    }

    AnaliseErrTableModel modelo = new AnaliseErrTableModel();
    private ErroBEAN erro;

    /**
     * Creates new form Avisos
     */
    public AnaliseErros(JLabel loading) {
        initComponents();
        this.loading = loading;

        tblErros.setModel(modelo);
        atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        tblErros = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        taDescErro = new javax.swing.JTextArea();
        btnProcSol = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        tfSol = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ANÁLISE DE ERROS");
        setAutoscrolls(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/suporte.png"))); // NOI18N

        tblErros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblErros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblErrosMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblErros);

        taDescErro.setColumns(20);
        taDescErro.setLineWrap(true);
        taDescErro.setRows(5);
        jScrollPane7.setViewportView(taDescErro);

        btnProcSol.setText("PROCEDER SOLUÇÃO");
        btnProcSol.setEnabled(false);
        btnProcSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcSolActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tfSol.setAutoscrolls(false);
        tfSol.setBorder(javax.swing.BorderFactory.createTitledBorder("SOLUÇÃO"));
        tfSol.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 182, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcSol))
                    .addComponent(tfSol)
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProcSol)
                            .addComponent(btnExcluir))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblErrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblErrosMouseClicked
        erro = modelo.getValueAt(tblErros.getSelectedRow());
        taDescErro.setText(erro.getDescricao());
        tfSol.setText(erro.getSts());
        btnExcluir.setEnabled(true);
        btnProcSol.setEnabled(true);
        tfSol.setEnabled(true);
    }//GEN-LAST:event_tblErrosMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            ErroDAO.excluiErr(erro.getId());
            JOptionPane.showMessageDialog(null, "EXCEÇÃO EXCLUÍDA COM SUCESSO!",
                    "ATENÇÃO",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "A OPERAÇÃO NÃO PODE SER REALIZADA NO MOMENTO."
                    + "\nTENTE NOVAMENTE MAIS TARDE. " + ex,
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnProcSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcSolActionPerformed
        try {
            erro.setSts(tfSol.getText());
            ErroDAO.atualizaStsErr(erro);
            JOptionPane.showMessageDialog(null, "SOLUÇÃO ATUALIZADA COM SUCESSO!",
                    "ATENÇÃO",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "A OPERAÇÃO NÃO PODE SER REALIZADA NO MOMENTO."
                    + "\nTENTE NOVAMENTE MAIS TARDE. " + ex,
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProcSolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnProcSol;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea taDescErro;
    private javax.swing.JTable tblErros;
    private javax.swing.JTextField tfSol;
    // End of variables declaration//GEN-END:variables
    private void atualizaTabela() {
        new Thread("Carrega erros") {
            @Override
            public void run() {
                try {
                    modelo.setNumRows(0);
                    for (ErroBEAN erro : ErroDAO.retornaErros()) {
                        modelo.addRow(erro);
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "A OPERAÇÃO NÃO PODE SER REALIZADA NO MOMENTO."
                            + "\nTENTE NOVAMENTE MAIS TARDE. " + ex,
                            "ERRO",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }.start();
    }
}
