/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.administrador;

import exception.EnvioExcecao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import ui.controle.Controle;

/**
 *
 * @author claud
 */
public class Avisos extends javax.swing.JInternalFrame {

    private JLabel loading;

    public static Avisos getInstancia(JLabel loading) {
        return new Avisos(loading);
    }

    /**
     * Creates new form Avisos
     */
    public Avisos(JLabel loading) {
        initComponents();
        this.loading = loading;

        new Thread("Carrega avisos") {
            @Override
            public void run() {
                try {
                    List<String> avisos = Controle.retornaAvisos();
                    for (int i = 0; i < avisos.size(); i++) {
                        switch (i) {
                            case 0:
                                taAvOrc.setText(avisos.get(i));
                                break;
                            case 1:
                                taAvProd.setText(avisos.get(i));
                                break;
                            case 2:
                                taAvExp.setText(avisos.get(i));
                                break;
                            case 3:
                                taAvFin.setText(avisos.get(i));
                                break;
                            case 4:
                                taAvOrd.setText(avisos.get(i));
                                break;
                        }
                    }
                } catch (SQLException ex) {
                    EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
                    EnvioExcecao.envio();
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnOrcamento = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAvOrc = new javax.swing.JTextArea();
        pnProducao = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taAvProd = new javax.swing.JTextArea();
        pnExpedicao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAvExp = new javax.swing.JTextArea();
        pnFinanceiro = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taAvFin = new javax.swing.JTextArea();
        pnOrdenador = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taAvOrd = new javax.swing.JTextArea();
        btnAt = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("AVISOS");
        setAutoscrolls(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/tutoriais.png"))); // NOI18N

        taAvOrc.setColumns(20);
        taAvOrc.setLineWrap(true);
        taAvOrc.setRows(5);
        taAvOrc.setToolTipText("");
        jScrollPane2.setViewportView(taAvOrc);

        javax.swing.GroupLayout pnOrcamentoLayout = new javax.swing.GroupLayout(pnOrcamento);
        pnOrcamento.setLayout(pnOrcamentoLayout);
        pnOrcamentoLayout.setHorizontalGroup(
            pnOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        pnOrcamentoLayout.setVerticalGroup(
            pnOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ORÇAMENTO", new javax.swing.ImageIcon(getClass().getResource("/icones/orçamento.png")), pnOrcamento); // NOI18N

        taAvProd.setColumns(20);
        taAvProd.setLineWrap(true);
        taAvProd.setRows(5);
        taAvProd.setToolTipText("");
        jScrollPane3.setViewportView(taAvProd);

        javax.swing.GroupLayout pnProducaoLayout = new javax.swing.GroupLayout(pnProducao);
        pnProducao.setLayout(pnProducaoLayout);
        pnProducaoLayout.setHorizontalGroup(
            pnProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        pnProducaoLayout.setVerticalGroup(
            pnProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("PRODUÇÃO", new javax.swing.ImageIcon(getClass().getResource("/icones/producao.png")), pnProducao); // NOI18N

        taAvExp.setColumns(20);
        taAvExp.setLineWrap(true);
        taAvExp.setRows(5);
        taAvExp.setToolTipText("");
        jScrollPane1.setViewportView(taAvExp);

        javax.swing.GroupLayout pnExpedicaoLayout = new javax.swing.GroupLayout(pnExpedicao);
        pnExpedicao.setLayout(pnExpedicaoLayout);
        pnExpedicaoLayout.setHorizontalGroup(
            pnExpedicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        pnExpedicaoLayout.setVerticalGroup(
            pnExpedicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("EXPEDIÇÃO", new javax.swing.ImageIcon(getClass().getResource("/icones/carrinho.png")), pnExpedicao); // NOI18N

        taAvFin.setColumns(20);
        taAvFin.setLineWrap(true);
        taAvFin.setRows(5);
        taAvFin.setToolTipText("");
        jScrollPane4.setViewportView(taAvFin);

        javax.swing.GroupLayout pnFinanceiroLayout = new javax.swing.GroupLayout(pnFinanceiro);
        pnFinanceiro.setLayout(pnFinanceiroLayout);
        pnFinanceiroLayout.setHorizontalGroup(
            pnFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        pnFinanceiroLayout.setVerticalGroup(
            pnFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("FINANCEIRO", new javax.swing.ImageIcon(getClass().getResource("/icones/financeiro.png")), pnFinanceiro); // NOI18N

        taAvOrd.setColumns(20);
        taAvOrd.setLineWrap(true);
        taAvOrd.setRows(5);
        taAvOrd.setToolTipText("");
        jScrollPane5.setViewportView(taAvOrd);

        javax.swing.GroupLayout pnOrdenadorLayout = new javax.swing.GroupLayout(pnOrdenador);
        pnOrdenador.setLayout(pnOrdenadorLayout);
        pnOrdenadorLayout.setHorizontalGroup(
            pnOrdenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        pnOrdenadorLayout.setVerticalGroup(
            pnOrdenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ORD DE DESPESAS", new javax.swing.ImageIcon(getClass().getResource("/icones/ordenador_despesas.png")), pnOrdenador); // NOI18N

        btnAt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/confirma.png"))); // NOI18N
        btnAt.setText("ATUALIZAR");
        btnAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAt)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtActionPerformed
        new Thread("Atualiza avisos") {
            @Override
            public void run() {
                try {
                    loading.setVisible(true);
                    loading.setText("ATUALIZANDO...");
                    List<String> avisos = new ArrayList();
                    avisos.add(taAvOrc.getText());
                    avisos.add(taAvProd.getText());
                    avisos.add(taAvExp.getText());
                    avisos.add(taAvFin.getText());
                    avisos.add(taAvOrd.getText());
                    Controle.atualizaAvisos(avisos);
                    JOptionPane.showMessageDialog(null,
                            "AVISOS ATUALIZADOS COM SUCESSO",
                            "CONFIRMAÇÃO",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
                    EnvioExcecao.envio();
                }
                loading.setVisible(false);
            }
        }.start();
    }//GEN-LAST:event_btnAtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnExpedicao;
    private javax.swing.JPanel pnFinanceiro;
    private javax.swing.JPanel pnOrcamento;
    private javax.swing.JPanel pnOrdenador;
    private javax.swing.JPanel pnProducao;
    public static javax.swing.JTextArea taAvExp;
    public static javax.swing.JTextArea taAvFin;
    public static javax.swing.JTextArea taAvOrc;
    public static javax.swing.JTextArea taAvOrd;
    public static javax.swing.JTextArea taAvProd;
    // End of variables declaration//GEN-END:variables
}
