/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ordemProducao.enviar;

import ui.login.TelaAutenticacao;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import entities.sisgrafex.OrdemProducao;
import entities.sisgrafex.CalculosOpBEAN;
import exception.EnvioExcecao;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.dao.OrcamentoDAO;
import model.dao.OrdemProducaoDAO;
import ui.cadastros.clientes.ClienteDAO;
import ui.cadastros.produtos.ProdutoDAO;
import ui.controle.Controle;
import ui.orcamentos.operacoes.OrcamentoPrincipalFrame;
import ui.principal.GerenteJanelas;

/**
 *
 * @author claud
 */
public class EnviarOrdemProducaoFrame extends javax.swing.JInternalFrame {

    public static int ORC_BASE = 0;
    private static int COD_CONTATO = 0;
    private static int COD_ENDERECO = 0;
    private static double VLR_ORC = 0d;
    private static byte TIPO_PROD = 0;

    public static byte getTIPO_PROD() {
        return TIPO_PROD;
    }

    public static void setTIPO_PROD(byte TIPO_PROD) {
        EnviarOrdemProducaoFrame.TIPO_PROD = TIPO_PROD;
    }

    public static double getVLR_ORC() {
        return VLR_ORC;
    }

    public static void setVLR_ORC(double VLR_ORC) {
        EnviarOrdemProducaoFrame.VLR_ORC = VLR_ORC;
    }

    public static int getCOD_CONTATO() {
        return COD_CONTATO;
    }

    public static void setCOD_CONTATO(int COD_CONTATO) {
        EnviarOrdemProducaoFrame.COD_CONTATO = COD_CONTATO;
    }

    public static int getCOD_ENDERECO() {
        return COD_ENDERECO;
    }

    public static void setCOD_ENDERECO(int COD_ENDERECO) {
        EnviarOrdemProducaoFrame.COD_ENDERECO = COD_ENDERECO;
    }

    private JLabel loading;
    private GerenteJanelas gj;

    private static EnviarOrdemProducaoFrame editarOpNovo;

    public static EnviarOrdemProducaoFrame getInstancia(JLabel loading, GerenteJanelas gj) {
        return new EnviarOrdemProducaoFrame(loading, gj);
    }

    /**
     * Creates new form OrcamentoEditarOpNovo
     *
     * @param loading
     * @param gj
     */
    public EnviarOrdemProducaoFrame(JLabel loading, GerenteJanelas gj) {
        initComponents();
        this.loading = loading;
        this.gj = gj;
        codigoOrcamentoBase.setEnabled(false);
        tipoPessoa.setEnabled(false);
        codigoCliente.setEnabled(false);
        nomeCliente.setEnabled(false);
        cpfCliente.setEnabled(false);
        cnpjCliente.setEnabled(false);
        nomeContato.setEnabled(false);
        telefoneContato.setEnabled(false);
        cidade.setEnabled(false);
        uf.setEnabled(false);
        observacoesOrdemProducao.setLineWrap(true);
        jbtnSelDtEntgProd.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nomeCliente = new javax.swing.JTextField();
        nomeContato = new javax.swing.JTextField();
        cidade = new javax.swing.JTextField();
        telefoneContato = new javax.swing.JTextField();
        uf = new javax.swing.JTextField();
        cpfCliente = new javax.swing.JFormattedTextField();
        cnpjCliente = new javax.swing.JFormattedTextField();
        tipoPessoa = new javax.swing.JTextField();
        codigoCliente = new javax.swing.JFormattedTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        observacoesOrdemProducao = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        codigoOrcamentoBase = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        confirmarEnvio = new javax.swing.JButton();
        tabPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        jbtnSelDtEntgProd = new javax.swing.JButton();
        jbtnSelDtEntgProva = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabelaQuantidades = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaPapeis = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelaAcabamentos = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaServicos = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObsFrete = new javax.swing.JTextArea();

        setTitle("ENVIAR ORDEM DE PRODUÇÃO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/producao.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        nomeCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("NOME DO CLIENTE"));

        nomeContato.setBorder(javax.swing.BorderFactory.createTitledBorder("NOME DO CONTATO"));

        cidade.setBorder(javax.swing.BorderFactory.createTitledBorder("CIDADE"));

        telefoneContato.setBorder(javax.swing.BorderFactory.createTitledBorder("TELEFONE PRINCIPAL"));

        uf.setBorder(javax.swing.BorderFactory.createTitledBorder("UF"));

        cpfCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF"));
        try {
            cpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cnpjCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("CNPJ"));
        try {
            cnpjCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tipoPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder("TIPO DE PESSOA"));

        codigoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("CÓDIGO DO CLIENTE"));
        codigoCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefoneContato, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cnpjCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cnpjCliente, cpfCliente});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpjCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(telefoneContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        observacoesOrdemProducao.setColumns(20);
        observacoesOrdemProducao.setRows(5);
        observacoesOrdemProducao.setBorder(javax.swing.BorderFactory.createTitledBorder("OBSERVAÇÕES"));
        jScrollPane5.setViewportView(observacoesOrdemProducao);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel31.setText("CÓDIGO DO ORÇAMENTO BASE: ");

        codigoOrcamentoBase.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        codigoOrcamentoBase.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "INFORMAÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        confirmarEnvio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/confirma.png"))); // NOI18N
        confirmarEnvio.setText("CONFIRMAR ENVIO");
        confirmarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarEnvioActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIÇÃO", "LARGURA", "ALTURA", "QTD. FOLHAS", "DT ENTG PROD", "DT ENTG PROVA", "OBSERVAÇÕES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        tabelaProdutos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabelaProdutosPropertyChange(evt);
            }
        });
        tabelaProdutos.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tabelaProdutosVetoableChange(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaProdutos);
        if (tabelaProdutos.getColumnModel().getColumnCount() > 0) {
            tabelaProdutos.getColumnModel().getColumn(0).setPreferredWidth(5);
            tabelaProdutos.getColumnModel().getColumn(1).setPreferredWidth(450);
            tabelaProdutos.getColumnModel().getColumn(2).setPreferredWidth(10);
            tabelaProdutos.getColumnModel().getColumn(3).setPreferredWidth(10);
            tabelaProdutos.getColumnModel().getColumn(4).setPreferredWidth(30);
            tabelaProdutos.getColumnModel().getColumn(5).setPreferredWidth(50);
            tabelaProdutos.getColumnModel().getColumn(6).setPreferredWidth(50);
            tabelaProdutos.getColumnModel().getColumn(7).setPreferredWidth(200);
        }

        jbtnSelDtEntgProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/periodo.png"))); // NOI18N
        jbtnSelDtEntgProd.setText("SELECIONAR DT ENTG PRODUTO");
        jbtnSelDtEntgProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelDtEntgProdActionPerformed(evt);
            }
        });

        jbtnSelDtEntgProva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/periodo.png"))); // NOI18N
        jbtnSelDtEntgProva.setText("SELECIONAR DT ENTG PROVA");
        jbtnSelDtEntgProva.setEnabled(false);
        jbtnSelDtEntgProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelDtEntgProvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSelDtEntgProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSelDtEntgProva)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSelDtEntgProd)
                    .addComponent(jbtnSelDtEntgProva))
                .addContainerGap())
        );

        tabPane.addTab("PRODUTOS", new javax.swing.ImageIcon(getClass().getResource("/icones/produto.png")), jPanel1); // NOI18N

        tabelaQuantidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓD PRODUTO", "QUANTIDADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tabelaQuantidades);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );

        tabPane.addTab("TIRAGENS", new javax.swing.ImageIcon(getClass().getResource("/icones/tiragens.png")), jPanel4); // NOI18N

        tabelaPapeis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓD PRODUTO", "CÓD PAPEL", "DESCRIÇÃO", "TIPO", "C.F", "C.V", "GASTO FOLHAS", "PERCA (%)", "FORMATO IMP.", "GASTO CHAPAS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelaPapeis);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );

        tabPane.addTab("PAPEL", new javax.swing.ImageIcon(getClass().getResource("/icones/papeis.png")), jPanel5); // NOI18N

        tabelaAcabamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓD PRODUTO", "CÓD ACABAMENTO", "DESCRIÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tabelaAcabamentos);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );

        tabPane.addTab("ACABAMENTOS", new javax.swing.ImageIcon(getClass().getResource("/icones/acabamentos.png")), jPanel7); // NOI18N

        tabelaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓD SERVIÇO", "DESCRIÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tabelaServicos);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );

        tabPane.addTab("SERVIÇOS", new javax.swing.ImageIcon(getClass().getResource("/icones/servicos_orcamento.png")), jPanel8); // NOI18N

        txtObsFrete.setColumns(20);
        txtObsFrete.setLineWrap(true);
        txtObsFrete.setRows(5);
        jScrollPane1.setViewportView(txtObsFrete);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );

        tabPane.addTab("OBSERVAÇÕES DO FRETE", new javax.swing.ImageIcon(getClass().getResource("/icones/transporte.png")), jPanel6); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(confirmarEnvio))
            .addComponent(tabPane)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoOrcamentoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoOrcamentoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarEnvioActionPerformed
        OrdemProducao op = new OrdemProducao();
        CalculosOpBEAN calculosBEAN = new CalculosOpBEAN();

        //VERIFICA SE EXISTEM PRODUTOS SEM A DATA DE ENTREGA SELECIONADA--------
        for (int i = 0; i < tabelaProdutos.getRowCount(); i++) {
            if (tabelaProdutos.getValueAt(i, 5).equals("")) {
                JOptionPane.showMessageDialog(null, "EXISTEM PRODUTOS SEM A DATA DE ENTREGA!\nSELECIONE A DATA DE TODOS OS PRODUTOS E TENTE NOVAMENTE.");
                return;
            }
        }
        //----------------------------------------------------------------------

        //INSTANCIA A LISTA DE OPS QUE SERÁ CRIADA------------------------------
        List listaOps = new ArrayList();
        //----------------------------------------------------------------------
        try {
            for (int i = 0; i < tabelaProdutos.getRowCount(); i++) {

                int codOp = OrdemProducaoDAO.retornaUltimoRegistro() + 1;
                int codProd = Integer.valueOf(tabelaProdutos.getValueAt(i, 0).toString());

                op.setCodigo(codOp);
                op.setOrcBase(ORC_BASE);
                op.setCodCliente(Integer.valueOf(codigoCliente.getValue().toString()));
                op.setTipoPessoa(tipoPessoa.getText().contains("FÍSICA") ? (byte) 1 : (byte) 2);
                op.setDataEmissao(new Date());
                op.setStatus(getTIPO_PROD() == 2 ? "ENCAMINHADO PARA EXPEDIÇÃO"
                        : "EM AVALIAÇÃO PELA SEÇ TÉCNICA");
                try {
                    op.setDataEntrega(Controle.dataPadrao.parse(tabelaProdutos.getValueAt(i, 5).toString()));
                    
                    
                    if(TIPO_PROD == 2){
                        op.setDataEntgProva(null);
                    }else{
                        op.setDataEntgProva(Controle.dataPadrao.parse(tabelaProdutos.getValueAt(i, 6).toString()));
                    }
                    
                } catch (ParseException ex) {
                    EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
                    EnvioExcecao.envio();
                    return;
                }
                op.setDescricao(observacoesOrdemProducao.getText());
                op.setCodEmissor(TelaAutenticacao.getUsrLogado().getCodigo());
                op.setCodProduto(codProd);
                op.setCodContato(COD_CONTATO);
                op.setCodEndereco(COD_ENDERECO);
                op.setTipoProduto(getTIPO_PROD());
                op.setObsFrete(txtObsFrete.getText().toUpperCase());
                OrdemProducaoDAO.createOp(op);

                if (codProd != 0) {
                    for (int j = 0; j < tabelaPapeis.getRowCount(); j++) {
                        if (tabelaPapeis.getValueAt(j, 0).equals(codProd)) {
                            OrdemProducaoDAO.alteraCalculosOp(ORC_BASE,
                                    codProd,
                                    getTIPO_PROD(),
                                    Integer.valueOf(tabelaPapeis.getValueAt(j, 1).toString()),
                                    codOp,
                                    tabelaPapeis.getValueAt(j, 3).toString());
                        }
                    }
                }

                switch(getTIPO_PROD()){
                    case 1:
                        OrcamentoDAO.alteraStatus(ORC_BASE, 2);
                        break;
                    case 2:
                        OrcamentoDAO.alteraStatus(ORC_BASE, 7);
                        break;
                }
                listaOps.add(codOp);

                /**
                 * Retira do estoque, caso pronta entrega
                 */
                if (getTIPO_PROD() == 2) {
                    ProdutoDAO.movEst(codProd,
                            Integer.valueOf(tabelaQuantidades.getValueAt(i, 1).toString()),
                            (byte) 1);
                }

            }

            /**
             * Desconta o crédito do cliente
             */
            switch (tipoPessoa.getText()) {
                case "PESSOA FÍSICA":
                    ClienteDAO.corrigeCredito(Integer.valueOf(codigoCliente.getValue().toString()),
                            (byte) 1,
                            VLR_ORC,
                            (byte) 2);
                    break;
                case "PESSOA JURÍDICA":
                    ClienteDAO.corrigeCredito(Integer.valueOf(codigoCliente.getValue().toString()),
                            (byte) 2,
                            VLR_ORC,
                            (byte) 2);
                    break;
            }

            /**
             * Atualiza o status do faturamento
             */
            OrcamentoDAO.atualizaStatusFaturamento(op.getOrcBase(), (byte) 1);

        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio();
        }

        if (getTIPO_PROD() == 2) {
            JOptionPane.showMessageDialog(null, "PEDIDO DE VENDA ENVIADO COM SUCESSO."
                    + "\nCÓDIGO DO(S) PEDIDO(OS) DE VENDA: "
                    + listaOps
                    + "\nDISPONÍVEL CONSULTA NA TELA DE CONSULTAS - ORDEM DE PRODUÇÃO.");
        } else {
            JOptionPane.showMessageDialog(null, "ORDEM DE PRODUÇÃO CRIADA COM SUCESSO."
                    + "\nCÓDIGO DA(S) ORDEM(NS) DE PRODUÇÃO: "
                    + listaOps
                    + "\nDISPONÍVEL CONSULTA NA TELA DE CONSULTAS - ORDEM DE PRODUÇÃO.");
        }

        OrcamentoPrincipalFrame.mostraTodos();
        this.dispose();
    }//GEN-LAST:event_confirmarEnvioActionPerformed

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        jbtnSelDtEntgProd.setEnabled(true);
        if(OrcamentoPrincipalFrame.getTIPO_ORCAMENTO() == 2){
            jbtnSelDtEntgProva.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void tabelaProdutosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabelaProdutosPropertyChange

    }//GEN-LAST:event_tabelaProdutosPropertyChange

    private void tabelaProdutosVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tabelaProdutosVetoableChange

    }//GEN-LAST:event_tabelaProdutosVetoableChange

    private void jbtnSelDtEntgProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelDtEntgProdActionPerformed
        DtEntregaProdutoFrame sdep = new DtEntregaProdutoFrame();
        sdep.setLocationRelativeTo(null);
        sdep.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        sdep.setTitle("DATA DE ENTREGA PRODUTO CÓD " + tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0));
        DtEntregaProdutoFrame.nLinha = tabelaProdutos.getSelectedRow();
        DtEntregaProdutoFrame.setTIPO((byte) 1);
        sdep.setVisible(true);
    }//GEN-LAST:event_jbtnSelDtEntgProdActionPerformed

    private void jbtnSelDtEntgProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelDtEntgProvaActionPerformed
        DtEntregaProdutoFrame sdep = new DtEntregaProdutoFrame();
        sdep.setLocationRelativeTo(null);
        sdep.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        sdep.setTitle("DATA DE ENTREGA DA PROVA DO PRODUTO CÓD " + tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0));
        DtEntregaProdutoFrame.nLinha = tabelaProdutos.getSelectedRow();
        DtEntregaProdutoFrame.setTIPO((byte) 2);
        sdep.setVisible(true);
    }//GEN-LAST:event_jbtnSelDtEntgProvaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField cidade;
    public static javax.swing.JFormattedTextField cnpjCliente;
    public static javax.swing.JFormattedTextField codigoCliente;
    public static javax.swing.JFormattedTextField codigoOrcamentoBase;
    private javax.swing.JButton confirmarEnvio;
    public static javax.swing.JFormattedTextField cpfCliente;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public static javax.swing.JButton jbtnSelDtEntgProd;
    public static javax.swing.JButton jbtnSelDtEntgProva;
    public static javax.swing.JTextField nomeCliente;
    public static javax.swing.JTextField nomeContato;
    public static javax.swing.JTextArea observacoesOrdemProducao;
    public static javax.swing.JTabbedPane tabPane;
    public static javax.swing.JTable tabelaAcabamentos;
    public static javax.swing.JTable tabelaPapeis;
    public static javax.swing.JTable tabelaProdutos;
    public static javax.swing.JTable tabelaQuantidades;
    public static javax.swing.JTable tabelaServicos;
    public static javax.swing.JTextField telefoneContato;
    public static javax.swing.JTextField tipoPessoa;
    private javax.swing.JTextArea txtObsFrete;
    public static javax.swing.JTextField uf;
    // End of variables declaration//GEN-END:variables

    //ESTADOS DA UI-------------------------------------------------------------
    public static void estadoPe() {
        tabPane.setEnabledAt(2, false);
        tabPane.setEnabledAt(3, false);
    }
}
