/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.cadastros.clientes;

import javax.swing.JFormattedTextField;
import javax.swing.JFormattedTextField.AbstractFormatterFactory;
import ui.orcamentos.operacoes.OrcamentoPrincipalFrame;

/**
 *
 * @author claud
 */
public class SelOrc extends javax.swing.JInternalFrame {

    private static SelOrc selecionarOrcamento;

    public static SelOrc getInstancia() {
        return new SelOrc();
    }

    /**
     * Creates new form SelecionarOrcamento
     */
    public SelOrc() {
        initComponents();
        cidade.setEnabled(false);
        uf.setEnabled(false);
        nomeContato.setEnabled(false);
        telefone.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        codigosContatos = new javax.swing.JComboBox<>();
        nomeContato = new javax.swing.JTextField();
        telefone = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        codigosEnderecos = new javax.swing.JComboBox<>();
        cidade = new javax.swing.JTextField();
        uf = new javax.swing.JTextField();
        selecionar = new javax.swing.JButton();

        setTitle("SELECIONAR PARA O ORÇAMENTO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/confirma.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("CONTATO"));

        codigosContatos.setBorder(javax.swing.BorderFactory.createTitledBorder("CÓDIGO"));
        codigosContatos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                codigosContatosItemStateChanged(evt);
            }
        });

        nomeContato.setBorder(javax.swing.BorderFactory.createTitledBorder("NOME PARA CONTATO"));

        telefone.setBorder(javax.swing.BorderFactory.createTitledBorder("TELEFONE PRINCIPAL"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigosContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigosContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {codigosContatos, nomeContato, telefone});

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ENDEREÇO"));

        codigosEnderecos.setBorder(javax.swing.BorderFactory.createTitledBorder("CÓDIGO"));
        codigosEnderecos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                codigosEnderecosItemStateChanged(evt);
            }
        });

        cidade.setBorder(javax.swing.BorderFactory.createTitledBorder("CIDADE"));

        uf.setBorder(javax.swing.BorderFactory.createTitledBorder("UF"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigosEnderecos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigosEnderecos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cidade, codigosEnderecos, uf});

        selecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/confirma.png"))); // NOI18N
        selecionar.setText("SELECIONAR");
        selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selecionar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selecionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigosContatosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_codigosContatosItemStateChanged
        if (codigosContatos.getSelectedItem().toString() != "SELECIONE...") {
            int cod = Integer.valueOf(codigosContatos.getSelectedItem().toString());
            for (int i = 0; i < ClienteCadastro.tabelaContatos.getRowCount(); i++) {
                if (Integer.valueOf(ClienteCadastro.tabelaContatos.getValueAt(i, 0).toString()) == cod) {
                    nomeContato.setText(ClienteCadastro.tabelaContatos.getValueAt(i, 1).toString());
                    telefone.setText(ClienteCadastro.tabelaContatos.getValueAt(i, 3).toString());
                }
            }
        }
    }//GEN-LAST:event_codigosContatosItemStateChanged

    private void codigosEnderecosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_codigosEnderecosItemStateChanged
        if (codigosEnderecos.getSelectedItem().toString() != "SELECIONE...") {
            int cod = Integer.valueOf(codigosEnderecos.getSelectedItem().toString());
            for (int i = 0; i < ClienteCadastro.tabelaEnderecos.getRowCount(); i++) {
                if (Integer.valueOf(ClienteCadastro.tabelaEnderecos.getValueAt(i, 0).toString()) == cod) {
                    cidade.setText(ClienteCadastro.tabelaEnderecos.getValueAt(i, 4).toString());
                    uf.setText(ClienteCadastro.tabelaEnderecos.getValueAt(i, 6).toString());
                }
            }
        }
    }//GEN-LAST:event_codigosEnderecosItemStateChanged

    private void selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarActionPerformed
        if (ClienteCadastro.orcamentoSelecionar == true) {
            if (ClienteCadastro.pessoaFisica.isSelected()) {
                OrcamentoPrincipalFrame.tipoPessoa.setText("PESSOA FÍSICA");
                OrcamentoPrincipalFrame.docCliente.setText(ClienteCadastro.cpf.getText());
            }
            if (ClienteCadastro.pessoaJuridica.isSelected()) {
                OrcamentoPrincipalFrame.tipoPessoa.setText("PESSOA JURÍDICA");
                OrcamentoPrincipalFrame.docCliente.setText(ClienteCadastro.cnpj.getText());
            }
            OrcamentoPrincipalFrame.codigoCliente.setValue(Integer.valueOf(ClienteCadastro.codigo.getText()));
            OrcamentoPrincipalFrame.nomeCliente.setText(ClienteCadastro.nomeCliente.getText());
            OrcamentoPrincipalFrame.nomeContatoCliente.setText(nomeContato.getText());
            OrcamentoPrincipalFrame.telefoneContatoCliente.setText(telefone.getText());
            OrcamentoPrincipalFrame.cidadeCliente.setText(cidade.getText());
            OrcamentoPrincipalFrame.ufCliente.setText(uf.getText());
            OrcamentoPrincipalFrame.CODIGO_CONTATO = Integer.valueOf(
                    codigosContatos.getSelectedItem().toString());
            OrcamentoPrincipalFrame.CODIGO_ENDERECO = Integer.valueOf(
                    codigosEnderecos.getSelectedItem().toString());
            OrcamentoPrincipalFrame.credito.setValue(Float.valueOf(
                    ClienteCadastro.creditoDisponivel.getValue().toString()));
        }
        if (ClienteCadastro.orcamentoEditarSelecionar == true) {
            if (ClienteCadastro.pessoaFisica.isSelected()) {
                OrcamentoPrincipalFrame.tipoPessoa.setText("PESSOA FÍSICA");
                OrcamentoPrincipalFrame.docCliente.setText(ClienteCadastro.cpf.getText());
            }
            if (ClienteCadastro.pessoaJuridica.isSelected()) {
                OrcamentoPrincipalFrame.tipoPessoa.setText("PESSOA JURÍDICA");
                OrcamentoPrincipalFrame.docCliente.setText(ClienteCadastro.cnpj.getText());
            }
            OrcamentoPrincipalFrame.codigoCliente.setValue(Integer.valueOf(ClienteCadastro.codigo.getText()));
            OrcamentoPrincipalFrame.nomeCliente.setText(ClienteCadastro.nomeCliente.getText());
            OrcamentoPrincipalFrame.nomeContatoCliente.setText(nomeContato.getText());
            OrcamentoPrincipalFrame.telefoneContatoCliente.setText(telefone.getText());
            OrcamentoPrincipalFrame.cidadeCliente.setText(cidade.getText());
            OrcamentoPrincipalFrame.ufCliente.setText(uf.getText());
            OrcamentoPrincipalFrame.CODIGO_CONTATO = Integer.valueOf(codigosContatos.getSelectedItem().toString());
            OrcamentoPrincipalFrame.CODIGO_ENDERECO = Integer.valueOf(codigosEnderecos.getSelectedItem().toString());
        }
        this.dispose();
    }//GEN-LAST:event_selecionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cidade;
    public static javax.swing.JComboBox<String> codigosContatos;
    public static javax.swing.JComboBox<String> codigosEnderecos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nomeContato;
    private javax.swing.JButton selecionar;
    private javax.swing.JTextField telefone;
    private javax.swing.JTextField uf;
    // End of variables declaration//GEN-END:variables

}
