/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.cadastros.servicos;

import javax.swing.JOptionPane;

/**
 *
 * @author spd3
 */
public class ServicosEditar extends javax.swing.JFrame {

    /**
     * Creates new form servicos_orcamento_editar
     */
    public ServicosEditar() {
        initComponents();

        codigo_editar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigo_editar = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        descricao_editar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valor_minimo_editar = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        valor_unitario_editar = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        servico_geral_editar = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        tipo_servico_editar = new javax.swing.JComboBox<String>();
        confirmar_alteracoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código:");

        codigo_editar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel2.setText("Descrição:");

        jLabel3.setText("Valor Mínimo:");

        valor_minimo_editar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel4.setText("Valor Unitário:");

        valor_unitario_editar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel5.setText("Serviço Geral?");

        servico_geral_editar.setText("Sim");

        jLabel6.setText("Tipo de Serviço:");

        tipo_servico_editar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Serviço Interno", "Serviço Externo" }));

        confirmar_alteracoes.setText("Confirmar Alterações");
        confirmar_alteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar_alteracoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmar_alteracoes)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codigo_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(descricao_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valor_minimo_editar))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valor_unitario_editar))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(servico_geral_editar)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tipo_servico_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricao_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_minimo_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_unitario_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servico_geral_editar)
                    .addComponent(tipo_servico_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(confirmar_alteracoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmar_alteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar_alteracoesActionPerformed
        ServicoBEAN sBEAN = new ServicoBEAN();
        ServicoDAO sDAO = new ServicoDAO();
        if(descricao_editar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Insira um valor no campo Descrição.");
            return;
        }else{
            sBEAN.setDescricao(descricao_editar.getText().toUpperCase());
        }
        if(valor_minimo_editar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Insira um valor no campo Valor Mínimo.");
            return;
        }else{
            String n2 = String.valueOf(valor_minimo_editar.getValue().toString());
            n2 = n2.replace(",", ".");
            float n3 = Float.valueOf(n2);
            sBEAN.setValorMinimo(n3);
        }
        if(valor_unitario_editar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Insira um valor no campo Valor Unitário.");
            return;
        }else{
            String n2 = String.valueOf(valor_unitario_editar.getValue().toString());
            n2 = n2.replace(",", ".");
            float n3 = Float.valueOf(n2);
            sBEAN.setValorUnitario(n3);
        }
        if(servico_geral_editar.isSelected()){
            sBEAN.setServicoGeral(1);
        }else{
            sBEAN.setServicoGeral(0);
        }
        if(tipo_servico_editar.getSelectedItem().equals("Selecione...")){
            JOptionPane.showMessageDialog(null, "Insira um Tipo de Serviço.");
            return;
        }else{
            sBEAN.setTipoServico(tipo_servico_editar.getSelectedItem().toString());
        }
        //sDAO.atualizaSv((int) codigo_editar.getValue(), sBEAN);
        
        this.dispose();
    }//GEN-LAST:event_confirmar_alteracoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicosEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicosEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicosEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicosEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServicosEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JFormattedTextField codigo_editar;
    private javax.swing.JButton confirmar_alteracoes;
    public static javax.swing.JTextField descricao_editar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JCheckBox servico_geral_editar;
    public static javax.swing.JComboBox<String> tipo_servico_editar;
    public static javax.swing.JFormattedTextField valor_minimo_editar;
    public static javax.swing.JFormattedTextField valor_unitario_editar;
    // End of variables declaration//GEN-END:variables
}
