/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.cadastros.servicos;

import exception.EnvioExcecao;
import exception.ErroPesquisa;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ui.controle.Controle;
import ui.orcamentos.operacoes.OrcamentoPrincipalFrame;
import ui.principal.GerenteJanelas;

/**
 *
 * @author claud
 */
public class ServicosFrame extends javax.swing.JInternalFrame {

    public static boolean orcamentoPrincipal;
    public static boolean orcamentoEditar;
    private JLabel loading;
    private GerenteJanelas gj;
    /**
     * 1 - EDITANDO 2 - NOVO 3 - ATUALIZANDO PREÇO
     */
    private byte EDITANDO;
    /**
     * Código do serviço
     */
    private int CODIGO;

    private static ServicosFrame servicosCadastroNovo;

    public static ServicosFrame getInstancia(JLabel loading, GerenteJanelas gj) {
        return new ServicosFrame(loading, gj);
    }

    /**
     * Creates new form ServicosCadastroNovo
     */
    public ServicosFrame(JLabel loading, GerenteJanelas gj) {
        this.EDITANDO = 0;
        this.loading = loading;
        this.gj = gj;
        this.CODIGO = 0;

        initComponents();

        btnSelecionar.setEnabled(false);
        btnDesativar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsServico = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        tfDescricao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        ftVlrMin = new javax.swing.JFormattedTextField();
        ftVlrUnit = new javax.swing.JFormattedTextField();
        ckSvGeral = new javax.swing.JCheckBox();
        cbTipoSv = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        spTblConsulta = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnDesativar = new javax.swing.JButton();
        cbTipoPesquisa = new javax.swing.JComboBox<>();
        tfPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();

        setTitle("SERVIÇOS DO ORÇAMENTO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/servicos_orcamento.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(566, 443));

        tfDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder("DESCRIÇÃO"));

        jLabel10.setText("SERVIÇO GERAL");

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/gravar.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        ftVlrMin.setBorder(javax.swing.BorderFactory.createTitledBorder("VALOR MÍNIMO"));
        ftVlrMin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        ftVlrMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftVlrMinActionPerformed(evt);
            }
        });

        ftVlrUnit.setBorder(javax.swing.BorderFactory.createTitledBorder("VALOR UNITÁRIO"));
        ftVlrUnit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        ckSvGeral.setText("SIM");
        ckSvGeral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cbTipoSv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Serviço Interno", "Serviço Externo" }));
        cbTipoSv.setBorder(javax.swing.BorderFactory.createTitledBorder("TIPO DE SERVIÇO"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ftVlrMin, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(cbTipoSv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(ckSvGeral)
                            .addGap(33, 33, 33)))
                    .addComponent(ftVlrUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tfDescricao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftVlrMin, ftVlrUnit});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ckSvGeral, jLabel10});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftVlrMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftVlrUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cbTipoSv, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckSvGeral)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabsServico.addTab("NOVO/EDITAR", new javax.swing.ImageIcon(getClass().getResource("/icones/novo_editar.png")), jPanel2); // NOI18N

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIÇÃO", "VALOR MÍNIMO", "VALOR UNITÁRIO", "SERVIÇO GERAL", "TIPO DE SERVIÇO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsultaMouseClicked(evt);
            }
        });
        spTblConsulta.setViewportView(tblConsulta);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnDesativar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/desativar.png"))); // NOI18N
        btnDesativar.setText("DESATIVAR");
        btnDesativar.setEnabled(false);
        btnDesativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesativarActionPerformed(evt);
            }
        });

        cbTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Código", "Descrição", "Tipo Serviço" }));
        cbTipoPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("PESQUISAR POR"));
        cbTipoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoPesquisaActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnMostrarTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ultimos.png"))); // NOI18N
        btnMostrarTodos.setText("MOSTRAR TODOS");
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });

        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/confirma.png"))); // NOI18N
        btnSelecionar.setText("SELECIONAR");
        btnSelecionar.setEnabled(false);
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarTodos)
                    .addComponent(btnPesquisar)))
            .addComponent(spTblConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesativar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecionar))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMostrarTodos, btnPesquisar});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrarTodos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTblConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnDesativar)
                    .addComponent(btnSelecionar))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbTipoPesquisa, tfPesquisa});

        tabsServico.addTab("CONSULTAS", new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsServico, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsServico)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            ServicoBEAN servico = new ServicoBEAN();
            servico.setCod(CODIGO);
            if (tfDescricao.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "INSIRA UM VALOR NO CAMPO DESCRIÇÃO!");
                return;
            } else {
                servico.setDescricao(tfDescricao.getText().toUpperCase());
            }
            if (ftVlrMin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "INSIRA UM VALOR NO CAMPO VALOR MÍNIMO!");
                return;
            } else {
                servico.setValorMinimo(Float.valueOf(ftVlrMin.getValue().toString()));
            }
            if (ftVlrUnit.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "INSIRA UM VALOR NO CAMPO VALOR UNITÁRIO!");
                return;
            } else {
                servico.setValorUnitario(Float.valueOf(ftVlrUnit.getValue().toString()));
            }
            servico.setServicoGeral(ckSvGeral.isSelected() ? 1 : 0);
            if (cbTipoSv.getSelectedItem().toString().equals("Selecione...")) {
                JOptionPane.showMessageDialog(null, "SELECIONE UM TIPO DE SERVIÇO.");
                return;
            } else {
                servico.setTipoServico(cbTipoSv.getSelectedItem().toString());
            }
            switch (EDITANDO) {
                case 1:
                case 3:
                    servico.setCod(CODIGO);
                    ServicoDAO.atualizaSv(servico);
                    JOptionPane.showMessageDialog(null,
                            "SERVIÇO ATUALIZADO COM SUCESSO",
                            "AVISO",
                            JOptionPane.INFORMATION_MESSAGE);
                    break;
                default:
                    ServicoDAO.cria(servico);
                    JOptionPane.showMessageDialog(null,
                            "SERVIÇO SALVO COM SUCESSO",
                            "AVISO",
                            JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
            limpa();
            EDITANDO = 2;
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void ftVlrMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftVlrMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftVlrMinActionPerformed

    private void tblConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultaMouseClicked
        try {
            if (ServicoDAO.verificaUsoSv((int) tblConsulta.getValueAt(tblConsulta.getSelectedRow(), 0))) {
                EDITANDO = 3;
            }

            btnEditar.setEnabled(true);
            btnDesativar.setEnabled(true);
            btnSelecionar.setEnabled(true);
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio();
        }
    }//GEN-LAST:event_tblConsultaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            CODIGO = (int) tblConsulta.getValueAt(tblConsulta.getSelectedRow(), 0);
            ServicoBEAN servico = ServicoDAO.carregaEdicao(CODIGO);
            tfDescricao.setText(servico.getDescricao());
            ftVlrMin.setValue(servico.getValorMinimo());
            ftVlrUnit.setValue(servico.getValorUnitario());
            ckSvGeral.setSelected((servico.getServicoGeral() == 1));
            cbTipoSv.setSelectedItem(servico.getTipoServico());

            switch (EDITANDO) {
                case 3:
                    estadoAtualiza();
                    break;
                default:
                    EDITANDO = 1;
                    break;
            }
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDesativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesativarActionPerformed
        try {
            int codigoServico = (int) tblConsulta.getValueAt(tblConsulta.getSelectedRow(), 0);
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "EXCLUIR REGISTRO Nº " + codigoServico + " ?", "CONFIRMAÇÃO DE EXCLUSÃO", dialogButton);
            if (dialogResult == 0) {
                ServicoDAO.desativaServico(codigoServico);
                DefaultTableModel modelo_consulta = (DefaultTableModel) tblConsulta.getModel();
                modelo_consulta.setNumRows(0);
                for (ServicoBEAN sBEAN : ServicoDAO.mostraTodos()) {
                    modelo_consulta.addRow(new Object[]{
                        sBEAN.getCod(),
                        sBEAN.getDescricao(),
                        sBEAN.getValorMinimo(),
                        sBEAN.getValorUnitario(),
                        sBEAN.getServicoGeral(),
                        sBEAN.getTipoServico()});
                }
            }
            btnDesativar.setEnabled(false);
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio();
        }
    }//GEN-LAST:event_btnDesativarActionPerformed

    private void cbTipoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoPesquisaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            DefaultTableModel modelo_consulta = (DefaultTableModel) tblConsulta.getModel();
            modelo_consulta.setNumRows(0);
            String servico_geral;
            for (ServicoBEAN sb : ServicoDAO.pesquisaReg((String) cbTipoPesquisa.getSelectedItem(), 
                    tfPesquisa.getText())) {
                if (sb.getServicoGeral() == 1) {
                    servico_geral = "SIM";
                } else {
                    servico_geral = "NÃO";
                }
                modelo_consulta.addRow(new Object[]{
                    sb.getCod(),
                    sb.getDescricao(),
                    sb.getValorMinimo(),
                    sb.getValorUnitario(),
                    servico_geral,
                    sb.getTipoServico()});
            }
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio();
        }catch(ErroPesquisa ex){
            JOptionPane.showMessageDialog(null, 
                    "VERIFIQUE OS PARÂMETROS DE PESQUISA E TENTE NOVAMENTE",
                    "ERRO AO PESQUISAR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        try {
            DefaultTableModel modeloConsulta = (DefaultTableModel) tblConsulta.getModel();
            modeloConsulta.setNumRows(0);
            String servico_geral;
            for (ServicoBEAN servico : ServicoDAO.mostraTodos()) {
                if (servico.getServicoGeral() == 1) {
                    servico_geral = "SIM";
                } else {
                    servico_geral = "NÃO";
                }
                modeloConsulta.addRow(new Object[]{
                    servico.getCod(),
                    servico.getDescricao(),
                    servico.getValorMinimo(),
                    servico.getValorUnitario(),
                    servico_geral,
                    servico.getTipoServico()});
            }
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio();
        }
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        if (orcamentoPrincipal) {
            try {
                DefaultTableModel modeloServicos = (DefaultTableModel) OrcamentoPrincipalFrame.tabelaServicos.getModel();
                for (ServicoBEAN pcBEAN : ServicoDAO.carregaOrcamento((int) tblConsulta.getValueAt(tblConsulta.getSelectedRow(), 0))) {
                    modeloServicos.addRow(new Object[]{
                        pcBEAN.getCod(),
                        pcBEAN.getDescricao(),
                        pcBEAN.getValorUnitario()});
                }
                OrcamentoPrincipalFrame.estadoProdSv((byte) 1);
            } catch (SQLException ex) {
                EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
                EnvioExcecao.envio();
            }
        }
        orcamentoPrincipal = false;
        orcamentoEditar = false;
        this.dispose();
    }//GEN-LAST:event_btnSelecionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesativar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JComboBox<String> cbTipoPesquisa;
    private javax.swing.JComboBox<String> cbTipoSv;
    private javax.swing.JCheckBox ckSvGeral;
    private javax.swing.JFormattedTextField ftVlrMin;
    private javax.swing.JFormattedTextField ftVlrUnit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane spTblConsulta;
    public static javax.swing.JTabbedPane tabsServico;
    public static javax.swing.JTable tblConsulta;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables

    public void limpa() {
        tfDescricao.setText("");
        ftVlrMin.setText("");
        ftVlrUnit.setText("");
        ckSvGeral.setSelected(false);
        cbTipoSv.setSelectedIndex(0);

        tfDescricao.setEditable(true);
        ftVlrMin.setEditable(true);
        ftVlrUnit.setEditable(true);
        cbTipoSv.setEnabled(true);
        ckSvGeral.setEnabled(true);
    }

    private void estadoAtualiza() {
        tfDescricao.setEditable(false);
        ftVlrMin.setEditable(true);
        ftVlrUnit.setEditable(true);
        cbTipoSv.setEnabled(true);
        ckSvGeral.setEnabled(true);
        tabsServico.setSelectedIndex(0);
    }
}
