/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.cadastros.papeis;

import model.dao.PapelDAO;
import javax.swing.table.DefaultTableModel;
import entities.sisgrafex.Papel;
import exception.EnvioExcecao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import ui.cadastros.produtos.ProdutoFrame;
import ui.controle.Controle;

/**
 *
 * @author claud
 */
public class PapelCadastro extends javax.swing.JFrame {

    public static boolean listaPrecoPapeis;
    public static boolean listaPrecoPapeisEditar;

    public PapelCadastro() {
        initComponents();

        excluir.setEnabled(false);
        editar.setEnabled(false);
        selecionar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        descricaoPapel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        formatoPapel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        valorPapel = new javax.swing.JFormattedTextField();
        cadastrar_papel = new javax.swing.JButton();
        larguraPapel = new javax.swing.JFormattedTextField();
        alturaPapel = new javax.swing.JFormattedTextField();
        gramaturaPapel = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        umaFaceCheck = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsulta = new javax.swing.JTable();
        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tipo_pesquisa = new javax.swing.JComboBox<>();
        textoPesquisa = new javax.swing.JTextField();
        botao_pesquisar = new javax.swing.JButton();
        mostra_todos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        selecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("DESCRIÇÃO:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel8.setText("LARGURA:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 11, -1, -1));
        jPanel2.add(descricaoPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 330, -1));

        jLabel9.setText("ALTURA:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 11, -1, -1));

        jLabel10.setText("GRAMATURA:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 11, -1, -1));

        jLabel11.setText("FORMATO:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, -1, -1));
        jPanel2.add(formatoPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, 120, -1));

        jLabel12.setText("VALOR UNITÁRIO:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 70, -1, -1));

        valorPapel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPanel2.add(valorPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 89, 100, -1));

        cadastrar_papel.setText("CADASTRAR");
        cadastrar_papel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_papelActionPerformed(evt);
            }
        });
        jPanel2.add(cadastrar_papel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, -1, 40));

        larguraPapel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel2.add(larguraPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 31, 77, -1));

        alturaPapel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel2.add(alturaPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 31, 77, -1));

        gramaturaPapel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel2.add(gramaturaPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 31, 100, -1));

        jLabel1.setText("UMA FACE?");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 69, -1, -1));

        umaFaceCheck.setText("SIM");
        jPanel2.add(umaFaceCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 88, -1, -1));

        jTabbedPane1.addTab("NOVO", jPanel2);

        tabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIÇÃO", "MEDIDA", "GRAMATURA", "FORMATO", "UMA FACE", "VALOR UNITÁRIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaConsulta);
        if (tabelaConsulta.getColumnModel().getColumnCount() > 0) {
            tabelaConsulta.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        excluir.setText("EXCLUIR");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        jLabel13.setText("PESQUISA POR:");

        tipo_pesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Código", "Descrição", "Medida", "Gramatura", "Formato", "Valor Unitário" }));
        tipo_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_pesquisaActionPerformed(evt);
            }
        });

        botao_pesquisar.setText("PESQUISAR");
        botao_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesquisarActionPerformed(evt);
            }
        });

        mostra_todos.setText("MOSTRAR TODOS");
        mostra_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostra_todosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        selecionar.setText("SELECIONAR");
        selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selecionar)
                        .addGap(5, 5, 5)
                        .addComponent(excluir)
                        .addGap(5, 5, 5)
                        .addComponent(editar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tipo_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(textoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(botao_pesquisar)
                                .addGap(254, 254, 254)
                                .addComponent(mostra_todos)))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botao_pesquisar)
                        .addComponent(mostra_todos))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipo_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecionar)
                            .addComponent(excluir)
                            .addComponent(editar)))))
        );

        jTabbedPane1.addTab("CONSULTAS", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_papelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_papelActionPerformed
        try {
            Papel papel = new Papel();

            String medida;
            int largura;
            int altura;
            int uma_face;
            float valor_unitario;

            if (descricaoPapel.getText().equals(null)) {
                JOptionPane.showMessageDialog(null, "Insira um valor no campo Descrição.");
                return;
            } else {
                papel.setDescricao(descricaoPapel.getText().toUpperCase());
            }

            if (larguraPapel.getValue().equals(null)) {
                JOptionPane.showMessageDialog(null, "Insira um valor no campo Largura.");
                return;
            } else {
                String n2 = String.valueOf(larguraPapel.getValue().toString());
                largura = Integer.valueOf(n2);
            }

            if (alturaPapel.getValue().equals(null)) {
                JOptionPane.showMessageDialog(null, "Insira um valor no campo Altura.");
                return;
            } else {
                String n2 = String.valueOf(alturaPapel.getValue().toString());
                altura = Integer.valueOf(n2);
            }

            medida = largura + " X " + altura;
            System.out.println(medida);
            papel.setMedida(medida);

            if (gramaturaPapel.getValue().equals(null)) {
                JOptionPane.showMessageDialog(null, "Insira um valor no campo Gramatura.");
                return;
            } else {
                String n2 = String.valueOf(gramaturaPapel.getValue().toString());
                papel.setGramatura(Integer.valueOf(n2));
            }

            if (formatoPapel.getText().equals(null)) {
                JOptionPane.showMessageDialog(null, "Insira um valor no campo Formato.");
                return;
            } else {
                papel.setFormato(formatoPapel.getText().toUpperCase());
            }

            if (umaFaceCheck.isSelected()) {
                uma_face = 1;
            } else {
                uma_face = 0;
            }

            if (valorPapel.getValue().equals(null)) {
                JOptionPane.showMessageDialog(null, "Insira um valor no campo Valor Unitário.");
                return;
            } else {
                String n2 = String.valueOf(valorPapel.getValue().toString());
                n2 = n2.replace(",", ".");
                double n3 = Double.valueOf(n2);
                papel.setUnitario((float) n3);
            }

            PapelDAO.create(papel);

            limpa();
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio(null);
        }
    }//GEN-LAST:event_cadastrar_papelActionPerformed

    private void tabelaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaMouseClicked
        editar.setEnabled(true);
        excluir.setEnabled(true);
        if (listaPrecoPapeis | listaPrecoPapeisEditar) {
            selecionar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaConsultaMouseClicked

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        PapelDAO pcDAO = new PapelDAO();
        int cod = (int) tabelaConsulta.getValueAt(tabelaConsulta.getSelectedRow(), 0);
        PapelEditar pe = new PapelEditar();
        pe.setLocationRelativeTo(null);
        pe.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pe.setTitle("EDIÇÃO DE PAPÉIS");
        for (Papel pcBEAN : pcDAO.carregar_edicao(cod)) {
            float largura = 0;
            float altura = 0;
            String medida;
            int index_x = 0;
            if (pcBEAN.getMedida().contains("X")) {
                index_x = pcBEAN.getMedida().indexOf("X");
            } else if (pcBEAN.getMedida().contains("x")) {
                index_x = pcBEAN.getMedida().indexOf("x");
            }
            largura = Float.valueOf(pcBEAN.getMedida().substring(0, index_x - 1));
            altura = Float.valueOf(pcBEAN.getMedida().substring(index_x + 2));
            PapelEditar.codigoEditar.setValue(pcBEAN.getCod());
            PapelEditar.descricaoEditar.setText(pcBEAN.getDescricao());
            PapelEditar.larguraEditar.setValue(largura);
            PapelEditar.alturaEditar.setValue(altura);
            PapelEditar.gramaturaEditar.setValue(pcBEAN.getGramatura());
            PapelEditar.formato.setText(pcBEAN.getFormato());
            if (pcBEAN.getUma_face() == 1) {
                umaFaceCheck.setSelected(true);
            } else {
                umaFaceCheck.setSelected(false);
            }
            PapelEditar.vlrUnit.setValue(pcBEAN.getUnitario());
        }
        pe.setVisible(true);
    }//GEN-LAST:event_editarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        PapelDAO pcDAO = new PapelDAO();
        int cod = (int) tabelaConsulta.getValueAt(tabelaConsulta.getSelectedRow(), 0);
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "EXCLUIR REGISTRO Nº " + cod + " ?", "CONFIRMAÇÃO DE EXCLUSÃO", dialogButton);
        if (dialogResult == 0) {
            pcDAO.excluir_registro(cod);
            DefaultTableModel modelo_consulta = (DefaultTableModel) tabelaConsulta.getModel();
            modelo_consulta.setNumRows(0);
            for (Papel pcBEAN : pcDAO.mostraTodos()) {
                modelo_consulta.addRow(new Object[]{
                    pcBEAN.getCod(),
                    pcBEAN.getDescricao(),
                    pcBEAN.getMedida(),
                    pcBEAN.getGramatura(),
                    pcBEAN.getFormato(),
                    pcBEAN.getUma_face(),
                    pcBEAN.getUnitario()});
            }
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void tipo_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_pesquisaActionPerformed

    private void botao_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesquisarActionPerformed
        try {
            DefaultTableModel modelo_consulta = (DefaultTableModel) tabelaConsulta.getModel();
            modelo_consulta.setNumRows(0);
            String tipo = (String) tipo_pesquisa.getSelectedItem();
            String texto = textoPesquisa.getText();

            for (Papel papel : PapelDAO.pesquisaRegistro(tipo, texto)) {
                String i;
                if (papel.getUma_face() == 1) {
                    i = "SIM";
                } else {
                    i = "NÃO";
                }
                modelo_consulta.addRow(new Object[]{
                    papel.getCod(),
                    papel.getDescricao(),
                    papel.getMedida(),
                    papel.getGramatura(),
                    papel.getFormato(),
                    i,
                    papel.getUnitario()});
            }
        } catch (SQLException ex) {
            EnvioExcecao envioExcecao = new EnvioExcecao(Controle.getDefaultGj(), ex);
            EnvioExcecao.envio(null);
        }
    }//GEN-LAST:event_botao_pesquisarActionPerformed

    private void mostra_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostra_todosActionPerformed
        DefaultTableModel modelo_consulta = (DefaultTableModel) tabelaConsulta.getModel();
        modelo_consulta.setNumRows(0);
        PapelDAO papeisCadastroDAO = new PapelDAO();
        for (Papel pcBEAN : papeisCadastroDAO.mostraTodos()) {
            modelo_consulta.addRow(new Object[]{
                pcBEAN.getCod(),
                pcBEAN.getDescricao(),
                pcBEAN.getMedida(),
                pcBEAN.getGramatura(),
                pcBEAN.getFormato(),
                pcBEAN.getUma_face(),
                pcBEAN.getUnitario()});
        }
    }//GEN-LAST:event_mostra_todosActionPerformed

    private void selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarActionPerformed
        PapelDAO pcDAO = new PapelDAO();
        if (listaPrecoPapeis) {
            for (Papel pcBEAN : pcDAO.carregaOrcamento((int) tabelaConsulta.getValueAt(tabelaConsulta.getSelectedRow(), 0))) {
                ProdutoFrame.codigoPapel.setValue(pcBEAN.getCod());
                ProdutoFrame.descricaoPapel = pcBEAN.getDescricao();
                ProdutoFrame.tipoPapel.setEnabled(true);
                ProdutoFrame.coresFrente.setEnabled(true);
                ProdutoFrame.coresVerso.setEnabled(true);
                ProdutoFrame.concluirPapel.setEnabled(true);
                if (ProdutoFrame.jcbTipoProduto.toString().equals("LIVRO") && ProdutoFrame.inserir == true) {
                    ProdutoFrame.orelha.setEnabled(true);
                }
            }
        }
        listaPrecoPapeisEditar = false;
        listaPrecoPapeis = false;

        this.dispose();
    }//GEN-LAST:event_selecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PapelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PapelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PapelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PapelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PapelCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField alturaPapel;
    private javax.swing.JButton botao_pesquisar;
    private javax.swing.JButton cadastrar_papel;
    private javax.swing.JTextField descricaoPapel;
    private javax.swing.JButton editar;
    private javax.swing.JButton excluir;
    private javax.swing.JTextField formatoPapel;
    private javax.swing.JFormattedTextField gramaturaPapel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFormattedTextField larguraPapel;
    private javax.swing.JButton mostra_todos;
    private javax.swing.JButton selecionar;
    public static javax.swing.JTable tabelaConsulta;
    private javax.swing.JTextField textoPesquisa;
    private javax.swing.JComboBox<String> tipo_pesquisa;
    private javax.swing.JCheckBox umaFaceCheck;
    public static javax.swing.JFormattedTextField valorPapel;
    // End of variables declaration//GEN-END:variables
    public void limpa() {
        descricaoPapel.setText("");
        larguraPapel.setText("");
        alturaPapel.setText("");
        gramaturaPapel.setText("");
        formatoPapel.setText("");
        umaFaceCheck.setSelected(false);
        valorPapel.setText("");
    }

}
